# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alex\ericworkspace\UIDOS\MainWindow_NOVTRES.ui'
#
# Created: Mon Dec 10 11:44:05 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(854, 569)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(570, 0, 281, 511))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_46 = QtGui.QLabel(self.frame_6)
        self.label_46.setGeometry(QtCore.QRect(70, 0, 125, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(10, 50, 261, 451))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.treeView_2 = QtGui.QTreeView(self.frame_7)
        self.treeView_2.setGeometry(QtCore.QRect(10, 10, 241, 431))
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 251, 511))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_9 = QtGui.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 231, 61))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label = QtGui.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(70, 0, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.addpBtn = QtGui.QPushButton(self.frame_9)
        self.addpBtn.setGeometry(QtCore.QRect(20, 30, 91, 23))
        self.addpBtn.setObjectName(_fromUtf8("addpBtn"))
        self.addUnitProces = QtGui.QPushButton(self.frame_9)
        self.addUnitProces.setGeometry(QtCore.QRect(120, 30, 91, 23))
        self.addUnitProces.setObjectName(_fromUtf8("addUnitProces"))
        self.scrollArea = QtGui.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(10, 80, 231, 421))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 419))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.treeView = QtGui.QTreeView(self.scrollAreaWidgetContents)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_4.addWidget(self.treeView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_11 = QtGui.QFrame(self.centralWidget)
        self.frame_11.setGeometry(QtCore.QRect(260, 0, 301, 391))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.tabWidget = QtGui.QTabWidget(self.frame_11)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 281, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.frame_5 = QtGui.QFrame(self.tab_5)
        self.frame_5.setGeometry(QtCore.QRect(10, 130, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_55 = QtGui.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(10, 10, 72, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.readModeCmBox = QtGui.QComboBox(self.frame_5)
        self.readModeCmBox.setGeometry(QtCore.QRect(90, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readModeCmBox.setFont(font)
        self.readModeCmBox.setObjectName(_fromUtf8("readModeCmBox"))
        self.readModeCmBox.addItem(_fromUtf8(""))
        self.readModeCmBox.addItem(_fromUtf8(""))
        self.dataWaitLine = QtGui.QLabel(self.frame_5)
        self.dataWaitLine.setGeometry(QtCore.QRect(167, 10, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataWaitLine.setFont(font)
        self.dataWaitLine.setObjectName(_fromUtf8("dataWaitLine"))
        self.dataWaitTxt = QtGui.QLineEdit(self.frame_5)
        self.dataWaitTxt.setGeometry(QtCore.QRect(230, 10, 21, 16))
        self.dataWaitTxt.setObjectName(_fromUtf8("dataWaitTxt"))
        self.frame_4 = QtGui.QFrame(self.tab_5)
        self.frame_4.setGeometry(QtCore.QRect(10, 60, 261, 61))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.dataTypeLine = QtGui.QLabel(self.frame_4)
        self.dataTypeLine.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataTypeLine.setFont(font)
        self.dataTypeLine.setObjectName(_fromUtf8("dataTypeLine"))
        self.dataPathline = QtGui.QLabel(self.frame_4)
        self.dataPathline.setGeometry(QtCore.QRect(10, 40, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPathline.setFont(font)
        self.dataPathline.setObjectName(_fromUtf8("dataPathline"))
        self.dataTypeCmbBox = QtGui.QComboBox(self.frame_4)
        self.dataTypeCmbBox.setGeometry(QtCore.QRect(80, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataTypeCmbBox.setFont(font)
        self.dataTypeCmbBox.setObjectName(_fromUtf8("dataTypeCmbBox"))
        self.dataTypeCmbBox.addItem(_fromUtf8(""))
        self.dataTypeCmbBox.addItem(_fromUtf8(""))
        self.dataPathTxt = QtGui.QLineEdit(self.frame_4)
        self.dataPathTxt.setGeometry(QtCore.QRect(80, 40, 141, 16))
        self.dataPathTxt.setObjectName(_fromUtf8("dataPathTxt"))
        self.dataPathBrowse = QtGui.QPushButton(self.frame_4)
        self.dataPathBrowse.setGeometry(QtCore.QRect(230, 40, 20, 16))
        self.dataPathBrowse.setObjectName(_fromUtf8("dataPathBrowse"))
        self.dataFormatTxt = QtGui.QLineEdit(self.frame_4)
        self.dataFormatTxt.setGeometry(QtCore.QRect(200, 10, 51, 16))
        self.dataFormatTxt.setObjectName(_fromUtf8("dataFormatTxt"))
        self.frame_3 = QtGui.QFrame(self.tab_5)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 261, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.dataOperationModeline = QtGui.QLabel(self.frame_3)
        self.dataOperationModeline.setGeometry(QtCore.QRect(10, 10, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataOperationModeline.setFont(font)
        self.dataOperationModeline.setObjectName(_fromUtf8("dataOperationModeline"))
        self.proConfCmbBox = QtGui.QComboBox(self.frame_3)
        self.proConfCmbBox.setGeometry(QtCore.QRect(150, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.proConfCmbBox.setFont(font)
        self.proConfCmbBox.setObjectName(_fromUtf8("proConfCmbBox"))
        self.frame_8 = QtGui.QFrame(self.tab_5)
        self.frame_8.setGeometry(QtCore.QRect(10, 170, 261, 71))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.dataStartLine = QtGui.QLabel(self.frame_8)
        self.dataStartLine.setGeometry(QtCore.QRect(10, 10, 69, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataStartLine.setFont(font)
        self.dataStartLine.setObjectName(_fromUtf8("dataStartLine"))
        self.dataEndline = QtGui.QLabel(self.frame_8)
        self.dataEndline.setGeometry(QtCore.QRect(10, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataEndline.setFont(font)
        self.dataEndline.setObjectName(_fromUtf8("dataEndline"))
        self.starDateCmbBox = QtGui.QComboBox(self.frame_8)
        self.starDateCmbBox.setGeometry(QtCore.QRect(100, 10, 141, 16))
        self.starDateCmbBox.setObjectName(_fromUtf8("starDateCmbBox"))
        self.endDateCmbBox = QtGui.QComboBox(self.frame_8)
        self.endDateCmbBox.setGeometry(QtCore.QRect(100, 30, 141, 16))
        self.endDateCmbBox.setObjectName(_fromUtf8("endDateCmbBox"))
        self.LTReferenceRdBtn = QtGui.QRadioButton(self.frame_8)
        self.LTReferenceRdBtn.setGeometry(QtCore.QRect(30, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LTReferenceRdBtn.setFont(font)
        self.LTReferenceRdBtn.setObjectName(_fromUtf8("LTReferenceRdBtn"))
        self.frame_10 = QtGui.QFrame(self.tab_5)
        self.frame_10.setGeometry(QtCore.QRect(10, 250, 261, 71))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.dataInitialTimeLine = QtGui.QLabel(self.frame_10)
        self.dataInitialTimeLine.setGeometry(QtCore.QRect(30, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dataInitialTimeLine.setFont(font)
        self.dataInitialTimeLine.setObjectName(_fromUtf8("dataInitialTimeLine"))
        self.dataFinelTimeLine = QtGui.QLabel(self.frame_10)
        self.dataFinelTimeLine.setGeometry(QtCore.QRect(30, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.dataFinelTimeLine.setFont(font)
        self.dataFinelTimeLine.setObjectName(_fromUtf8("dataFinelTimeLine"))
        self.startTimeEdit = QtGui.QTimeEdit(self.frame_10)
        self.startTimeEdit.setGeometry(QtCore.QRect(110, 10, 131, 20))
        self.startTimeEdit.setObjectName(_fromUtf8("startTimeEdit"))
        self.timeEdit_2 = QtGui.QTimeEdit(self.frame_10)
        self.timeEdit_2.setGeometry(QtCore.QRect(110, 40, 131, 21))
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        self.dataOkBtn = QtGui.QPushButton(self.tab_5)
        self.dataOkBtn.setGeometry(QtCore.QRect(80, 320, 61, 21))
        self.dataOkBtn.setObjectName(_fromUtf8("dataOkBtn"))
        self.dataCancelBtn = QtGui.QPushButton(self.tab_5)
        self.dataCancelBtn.setGeometry(QtCore.QRect(150, 320, 61, 21))
        self.dataCancelBtn.setObjectName(_fromUtf8("dataCancelBtn"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_7)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 20, 261, 301))
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_13 = QtGui.QFrame(self.tab_3)
        self.frame_13.setGeometry(QtCore.QRect(10, 10, 231, 201))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.removeDCCEB = QtGui.QCheckBox(self.frame_13)
        self.removeDCCEB.setGeometry(QtCore.QRect(10, 100, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeDCCEB.setFont(font)
        self.removeDCCEB.setObjectName(_fromUtf8("removeDCCEB"))
        self.coherentIntegrationCEB = QtGui.QCheckBox(self.frame_13)
        self.coherentIntegrationCEB.setGeometry(QtCore.QRect(10, 170, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coherentIntegrationCEB.setFont(font)
        self.coherentIntegrationCEB.setObjectName(_fromUtf8("coherentIntegrationCEB"))
        self.removeDCcob = QtGui.QComboBox(self.frame_13)
        self.removeDCcob.setGeometry(QtCore.QRect(130, 100, 91, 20))
        self.removeDCcob.setObjectName(_fromUtf8("removeDCcob"))
        self.numberIntegration = QtGui.QLineEdit(self.frame_13)
        self.numberIntegration.setGeometry(QtCore.QRect(150, 170, 71, 21))
        self.numberIntegration.setObjectName(_fromUtf8("numberIntegration"))
        self.decodeCEB = QtGui.QCheckBox(self.frame_13)
        self.decodeCEB.setGeometry(QtCore.QRect(10, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.decodeCEB.setFont(font)
        self.decodeCEB.setObjectName(_fromUtf8("decodeCEB"))
        self.decodeCcob = QtGui.QComboBox(self.frame_13)
        self.decodeCcob.setGeometry(QtCore.QRect(130, 130, 91, 20))
        self.decodeCcob.setObjectName(_fromUtf8("decodeCcob"))
        self.profileOpVolcob = QtGui.QComboBox(self.frame_13)
        self.profileOpVolcob.setGeometry(QtCore.QRect(130, 40, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.profileOpVolcob.setFont(font)
        self.profileOpVolcob.setObjectName(_fromUtf8("profileOpVolcob"))
        self.profileOpVolcob.addItem(_fromUtf8(""))
        self.profileOpVolcob.addItem(_fromUtf8(""))
        self.selecChannelopVolCEB = QtGui.QCheckBox(self.frame_13)
        self.selecChannelopVolCEB.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.selecChannelopVolCEB.setObjectName(_fromUtf8("selecChannelopVolCEB"))
        self.selecHeighopVolCEB = QtGui.QCheckBox(self.frame_13)
        self.selecHeighopVolCEB.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.selecHeighopVolCEB.setObjectName(_fromUtf8("selecHeighopVolCEB"))
        self.numberChannelopVol = QtGui.QLineEdit(self.frame_13)
        self.numberChannelopVol.setEnabled(True)
        self.numberChannelopVol.setGeometry(QtCore.QRect(130, 10, 91, 20))
        self.numberChannelopVol.setObjectName(_fromUtf8("numberChannelopVol"))
        self.lineHeighProfileTxtopVol = QtGui.QLineEdit(self.frame_13)
        self.lineHeighProfileTxtopVol.setGeometry(QtCore.QRect(10, 70, 211, 20))
        self.lineHeighProfileTxtopVol.setObjectName(_fromUtf8("lineHeighProfileTxtopVol"))
        self.frame_14 = QtGui.QFrame(self.tab_3)
        self.frame_14.setGeometry(QtCore.QRect(10, 220, 231, 41))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.dataopVolOkBtn = QtGui.QPushButton(self.frame_14)
        self.dataopVolOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.dataopVolOkBtn.setObjectName(_fromUtf8("dataopVolOkBtn"))
        self.dataopVolCancelBtn = QtGui.QPushButton(self.frame_14)
        self.dataopVolCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.dataopVolCancelBtn.setObjectName(_fromUtf8("dataopVolCancelBtn"))
        self.tabWidget_3.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_17 = QtGui.QFrame(self.tab_2)
        self.frame_17.setGeometry(QtCore.QRect(10, 120, 231, 61))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.datalabelGraphicsVol = QtGui.QLabel(self.frame_17)
        self.datalabelGraphicsVol.setGeometry(QtCore.QRect(10, 10, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datalabelGraphicsVol.setFont(font)
        self.datalabelGraphicsVol.setObjectName(_fromUtf8("datalabelGraphicsVol"))
        self.dataPotlabelGraphicsVol = QtGui.QLabel(self.frame_17)
        self.dataPotlabelGraphicsVol.setGeometry(QtCore.QRect(10, 30, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPotlabelGraphicsVol.setFont(font)
        self.dataPotlabelGraphicsVol.setObjectName(_fromUtf8("dataPotlabelGraphicsVol"))
        self.showdataGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.showdataGraphicsVol.setGeometry(QtCore.QRect(140, 10, 31, 26))
        self.showdataGraphicsVol.setText(_fromUtf8(""))
        self.showdataGraphicsVol.setObjectName(_fromUtf8("showdataGraphicsVol"))
        self.savedataCEBGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.savedataCEBGraphicsVol.setGeometry(QtCore.QRect(190, 10, 31, 26))
        self.savedataCEBGraphicsVol.setText(_fromUtf8(""))
        self.savedataCEBGraphicsVol.setObjectName(_fromUtf8("savedataCEBGraphicsVol"))
        self.showPotCEBGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.showPotCEBGraphicsVol.setGeometry(QtCore.QRect(140, 30, 31, 26))
        self.showPotCEBGraphicsVol.setText(_fromUtf8(""))
        self.showPotCEBGraphicsVol.setObjectName(_fromUtf8("showPotCEBGraphicsVol"))
        self.checkBox_18 = QtGui.QCheckBox(self.frame_17)
        self.checkBox_18.setGeometry(QtCore.QRect(190, 30, 31, 26))
        self.checkBox_18.setText(_fromUtf8(""))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.frame_16 = QtGui.QFrame(self.tab_2)
        self.frame_16.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.dataPathlabelGraphicsVol = QtGui.QLabel(self.frame_16)
        self.dataPathlabelGraphicsVol.setGeometry(QtCore.QRect(10, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPathlabelGraphicsVol.setFont(font)
        self.dataPathlabelGraphicsVol.setObjectName(_fromUtf8("dataPathlabelGraphicsVol"))
        self.dataPrefixlabelGraphicsVol = QtGui.QLabel(self.frame_16)
        self.dataPrefixlabelGraphicsVol.setGeometry(QtCore.QRect(10, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPrefixlabelGraphicsVol.setFont(font)
        self.dataPrefixlabelGraphicsVol.setObjectName(_fromUtf8("dataPrefixlabelGraphicsVol"))
        self.dataPathtxtGraphicsVol = QtGui.QLineEdit(self.frame_16)
        self.dataPathtxtGraphicsVol.setGeometry(QtCore.QRect(50, 10, 141, 21))
        self.dataPathtxtGraphicsVol.setObjectName(_fromUtf8("dataPathtxtGraphicsVol"))
        self.dataGraphicsVolPathBrowse = QtGui.QToolButton(self.frame_16)
        self.dataGraphicsVolPathBrowse.setGeometry(QtCore.QRect(200, 10, 21, 21))
        self.dataGraphicsVolPathBrowse.setObjectName(_fromUtf8("dataGraphicsVolPathBrowse"))
        self.dataPrefixtxtGraphicsVol = QtGui.QLineEdit(self.frame_16)
        self.dataPrefixtxtGraphicsVol.setGeometry(QtCore.QRect(50, 40, 171, 21))
        self.dataPrefixtxtGraphicsVol.setObjectName(_fromUtf8("dataPrefixtxtGraphicsVol"))
        self.frame_18 = QtGui.QFrame(self.tab_2)
        self.frame_18.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_18.setObjectName(_fromUtf8("frame_18"))
        self.label_6 = QtGui.QLabel(self.frame_18)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame_18)
        self.label_7.setGeometry(QtCore.QRect(130, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame_18)
        self.label_8.setGeometry(QtCore.QRect(190, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_19 = QtGui.QFrame(self.tab_2)
        self.frame_19.setGeometry(QtCore.QRect(10, 180, 231, 61))
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.label_13 = QtGui.QLabel(self.frame_19)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_19)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_19)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 30, 101, 16))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.toolButton_2 = QtGui.QToolButton(self.frame_19)
        self.toolButton_2.setGeometry(QtCore.QRect(200, 30, 21, 16))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.comboBox_10 = QtGui.QComboBox(self.frame_19)
        self.comboBox_10.setGeometry(QtCore.QRect(90, 10, 131, 16))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.dataGraphVolOkBtn = QtGui.QPushButton(self.tab_2)
        self.dataGraphVolOkBtn.setGeometry(QtCore.QRect(60, 250, 71, 21))
        self.dataGraphVolOkBtn.setObjectName(_fromUtf8("dataGraphVolOkBtn"))
        self.dataGraphVolCancelBtn = QtGui.QPushButton(self.tab_2)
        self.dataGraphVolCancelBtn.setGeometry(QtCore.QRect(140, 250, 71, 21))
        self.dataGraphVolCancelBtn.setObjectName(_fromUtf8("dataGraphVolCancelBtn"))
        self.tabWidget_3.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.frame_15 = QtGui.QFrame(self.tab_4)
        self.frame_15.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.dataPathlabelOutVol = QtGui.QLabel(self.frame_15)
        self.dataPathlabelOutVol.setGeometry(QtCore.QRect(20, 10, 31, 16))
        self.dataPathlabelOutVol.setObjectName(_fromUtf8("dataPathlabelOutVol"))
        self.dataPathtxtOutVol = QtGui.QLineEdit(self.frame_15)
        self.dataPathtxtOutVol.setGeometry(QtCore.QRect(62, 10, 121, 20))
        self.dataPathtxtOutVol.setObjectName(_fromUtf8("dataPathtxtOutVol"))
        self.dataOutVolPathBrowse = QtGui.QToolButton(self.frame_15)
        self.dataOutVolPathBrowse.setGeometry(QtCore.QRect(190, 10, 25, 19))
        self.dataOutVolPathBrowse.setObjectName(_fromUtf8("dataOutVolPathBrowse"))
        self.dataSufixlabelOutVol = QtGui.QLabel(self.frame_15)
        self.dataSufixlabelOutVol.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.dataSufixlabelOutVol.setObjectName(_fromUtf8("dataSufixlabelOutVol"))
        self.dataSufixtxtOutVol = QtGui.QLineEdit(self.frame_15)
        self.dataSufixtxtOutVol.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.dataSufixtxtOutVol.setObjectName(_fromUtf8("dataSufixtxtOutVol"))
        self.frame_48 = QtGui.QFrame(self.tab_4)
        self.frame_48.setGeometry(QtCore.QRect(10, 140, 231, 41))
        self.frame_48.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_48.setObjectName(_fromUtf8("frame_48"))
        self.datasaveVolOkBtn = QtGui.QPushButton(self.frame_48)
        self.datasaveVolOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.datasaveVolOkBtn.setObjectName(_fromUtf8("datasaveVolOkBtn"))
        self.datasaveVolCancelBtn = QtGui.QPushButton(self.frame_48)
        self.datasaveVolCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.datasaveVolCancelBtn.setObjectName(_fromUtf8("datasaveVolCancelBtn"))
        self.tabWidget_3.addTab(self.tab_4, _fromUtf8(""))
        self.addOpUpselec = QtGui.QComboBox(self.tab_7)
        self.addOpUpselec.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.addOpUpselec.setObjectName(_fromUtf8("addOpUpselec"))
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_4.setGeometry(QtCore.QRect(9, 9, 261, 321))
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.frame_34 = QtGui.QFrame(self.tab_8)
        self.frame_34.setGeometry(QtCore.QRect(20, 20, 231, 191))
        self.frame_34.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_34.setObjectName(_fromUtf8("frame_34"))
        self.checkBox_49 = QtGui.QCheckBox(self.frame_34)
        self.checkBox_49.setGeometry(QtCore.QRect(10, 30, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_49.setFont(font)
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.checkBox_50 = QtGui.QCheckBox(self.frame_34)
        self.checkBox_50.setGeometry(QtCore.QRect(10, 70, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_50.setFont(font)
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.checkBox_51 = QtGui.QCheckBox(self.frame_34)
        self.checkBox_51.setGeometry(QtCore.QRect(10, 110, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_51.setFont(font)
        self.checkBox_51.setObjectName(_fromUtf8("checkBox_51"))
        self.checkBox_52 = QtGui.QCheckBox(self.frame_34)
        self.checkBox_52.setGeometry(QtCore.QRect(10, 160, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_52.setFont(font)
        self.checkBox_52.setObjectName(_fromUtf8("checkBox_52"))
        self.comboBox_21 = QtGui.QComboBox(self.frame_34)
        self.comboBox_21.setGeometry(QtCore.QRect(150, 30, 71, 20))
        self.comboBox_21.setObjectName(_fromUtf8("comboBox_21"))
        self.comboBox_22 = QtGui.QComboBox(self.frame_34)
        self.comboBox_22.setGeometry(QtCore.QRect(150, 70, 71, 20))
        self.comboBox_22.setObjectName(_fromUtf8("comboBox_22"))
        self.comboBox_23 = QtGui.QComboBox(self.frame_34)
        self.comboBox_23.setGeometry(QtCore.QRect(150, 130, 71, 20))
        self.comboBox_23.setObjectName(_fromUtf8("comboBox_23"))
        self.lineEdit_33 = QtGui.QLineEdit(self.frame_34)
        self.lineEdit_33.setGeometry(QtCore.QRect(150, 160, 71, 20))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.frame_35 = QtGui.QFrame(self.tab_8)
        self.frame_35.setGeometry(QtCore.QRect(10, 220, 231, 41))
        self.frame_35.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_35.setObjectName(_fromUtf8("frame_35"))
        self.dataopSpecOkBtn = QtGui.QPushButton(self.frame_35)
        self.dataopSpecOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.dataopSpecOkBtn.setObjectName(_fromUtf8("dataopSpecOkBtn"))
        self.dataopSpecCancelBtn = QtGui.QPushButton(self.frame_35)
        self.dataopSpecCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.dataopSpecCancelBtn.setObjectName(_fromUtf8("dataopSpecCancelBtn"))
        self.tabWidget_4.addTab(self.tab_8, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.dataGraphSpecCancelBtn = QtGui.QPushButton(self.tab_10)
        self.dataGraphSpecCancelBtn.setGeometry(QtCore.QRect(140, 270, 71, 21))
        self.dataGraphSpecCancelBtn.setObjectName(_fromUtf8("dataGraphSpecCancelBtn"))
        self.frame_39 = QtGui.QFrame(self.tab_10)
        self.frame_39.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.frame_39.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_39.setObjectName(_fromUtf8("frame_39"))
        self.label_80 = QtGui.QLabel(self.frame_39)
        self.label_80.setGeometry(QtCore.QRect(10, 0, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_81 = QtGui.QLabel(self.frame_39)
        self.label_81.setGeometry(QtCore.QRect(130, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.label_82 = QtGui.QLabel(self.frame_39)
        self.label_82.setGeometry(QtCore.QRect(190, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.frame_40 = QtGui.QFrame(self.tab_10)
        self.frame_40.setGeometry(QtCore.QRect(10, 120, 231, 101))
        self.frame_40.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_40.setObjectName(_fromUtf8("frame_40"))
        self.label_83 = QtGui.QLabel(self.frame_40)
        self.label_83.setGeometry(QtCore.QRect(10, 0, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.frame_40)
        self.label_84.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.label_85 = QtGui.QLabel(self.frame_40)
        self.label_85.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.label_86 = QtGui.QLabel(self.frame_40)
        self.label_86.setGeometry(QtCore.QRect(10, 60, 66, 21))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.checkBox_57 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_57.setGeometry(QtCore.QRect(150, 0, 31, 26))
        self.checkBox_57.setText(_fromUtf8(""))
        self.checkBox_57.setObjectName(_fromUtf8("checkBox_57"))
        self.checkBox_58 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_58.setGeometry(QtCore.QRect(190, 0, 31, 26))
        self.checkBox_58.setText(_fromUtf8(""))
        self.checkBox_58.setObjectName(_fromUtf8("checkBox_58"))
        self.checkBox_59 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_59.setGeometry(QtCore.QRect(150, 20, 31, 26))
        self.checkBox_59.setText(_fromUtf8(""))
        self.checkBox_59.setObjectName(_fromUtf8("checkBox_59"))
        self.checkBox_60 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_60.setGeometry(QtCore.QRect(190, 20, 31, 26))
        self.checkBox_60.setText(_fromUtf8(""))
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.checkBox_61 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_61.setGeometry(QtCore.QRect(150, 40, 31, 21))
        self.checkBox_61.setText(_fromUtf8(""))
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.checkBox_62 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_62.setGeometry(QtCore.QRect(190, 40, 31, 26))
        self.checkBox_62.setText(_fromUtf8(""))
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.checkBox_63 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_63.setGeometry(QtCore.QRect(150, 60, 20, 26))
        self.checkBox_63.setText(_fromUtf8(""))
        self.checkBox_63.setObjectName(_fromUtf8("checkBox_63"))
        self.label_100 = QtGui.QLabel(self.frame_40)
        self.label_100.setGeometry(QtCore.QRect(10, 80, 66, 21))
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.checkBox_64 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_64.setGeometry(QtCore.QRect(190, 60, 31, 26))
        self.checkBox_64.setText(_fromUtf8(""))
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.checkBox_73 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_73.setGeometry(QtCore.QRect(150, 80, 20, 26))
        self.checkBox_73.setText(_fromUtf8(""))
        self.checkBox_73.setObjectName(_fromUtf8("checkBox_73"))
        self.checkBox_74 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_74.setGeometry(QtCore.QRect(190, 80, 20, 26))
        self.checkBox_74.setText(_fromUtf8(""))
        self.checkBox_74.setObjectName(_fromUtf8("checkBox_74"))
        self.dataGraphSpecOkBtn = QtGui.QPushButton(self.tab_10)
        self.dataGraphSpecOkBtn.setGeometry(QtCore.QRect(60, 270, 71, 21))
        self.dataGraphSpecOkBtn.setObjectName(_fromUtf8("dataGraphSpecOkBtn"))
        self.frame_38 = QtGui.QFrame(self.tab_10)
        self.frame_38.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.frame_38.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_38.setObjectName(_fromUtf8("frame_38"))
        self.label_78 = QtGui.QLabel(self.frame_38)
        self.label_78.setGeometry(QtCore.QRect(10, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.label_79 = QtGui.QLabel(self.frame_38)
        self.label_79.setGeometry(QtCore.QRect(10, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.lineEdit_35 = QtGui.QLineEdit(self.frame_38)
        self.lineEdit_35.setGeometry(QtCore.QRect(50, 10, 141, 21))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.toolButton_17 = QtGui.QToolButton(self.frame_38)
        self.toolButton_17.setGeometry(QtCore.QRect(200, 10, 21, 21))
        self.toolButton_17.setObjectName(_fromUtf8("toolButton_17"))
        self.lineEdit_36 = QtGui.QLineEdit(self.frame_38)
        self.lineEdit_36.setGeometry(QtCore.QRect(50, 40, 171, 21))
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.frame_41 = QtGui.QFrame(self.tab_10)
        self.frame_41.setGeometry(QtCore.QRect(10, 220, 231, 51))
        self.frame_41.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_41.setObjectName(_fromUtf8("frame_41"))
        self.label_87 = QtGui.QLabel(self.frame_41)
        self.label_87.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.frame_41)
        self.label_88.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.lineEdit_37 = QtGui.QLineEdit(self.frame_41)
        self.lineEdit_37.setGeometry(QtCore.QRect(90, 30, 101, 16))
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.toolButton_18 = QtGui.QToolButton(self.frame_41)
        self.toolButton_18.setGeometry(QtCore.QRect(200, 30, 21, 16))
        self.toolButton_18.setObjectName(_fromUtf8("toolButton_18"))
        self.comboBox_27 = QtGui.QComboBox(self.frame_41)
        self.comboBox_27.setGeometry(QtCore.QRect(90, 10, 131, 16))
        self.comboBox_27.setObjectName(_fromUtf8("comboBox_27"))
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.label_22 = QtGui.QLabel(self.tab_11)
        self.label_22.setGeometry(QtCore.QRect(140, 100, 58, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.frame_47 = QtGui.QFrame(self.tab_11)
        self.frame_47.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.frame_47.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_47.setObjectName(_fromUtf8("frame_47"))
        self.label_20 = QtGui.QLabel(self.frame_47)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 22, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_47)
        self.lineEdit_11.setGeometry(QtCore.QRect(50, 10, 133, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.toolButton_5 = QtGui.QToolButton(self.frame_47)
        self.toolButton_5.setGeometry(QtCore.QRect(190, 10, 25, 19))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.label_21 = QtGui.QLabel(self.frame_47)
        self.label_21.setGeometry(QtCore.QRect(20, 40, 24, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_47)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 40, 171, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.frame_49 = QtGui.QFrame(self.tab_11)
        self.frame_49.setGeometry(QtCore.QRect(10, 130, 231, 41))
        self.frame_49.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_49.setObjectName(_fromUtf8("frame_49"))
        self.datasaveSpecOkBtn = QtGui.QPushButton(self.frame_49)
        self.datasaveSpecOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.datasaveSpecOkBtn.setObjectName(_fromUtf8("datasaveSpecOkBtn"))
        self.datasaveSpecCancelBtn = QtGui.QPushButton(self.frame_49)
        self.datasaveSpecCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.datasaveSpecCancelBtn.setObjectName(_fromUtf8("datasaveSpecCancelBtn"))
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.tabWidget_5 = QtGui.QTabWidget(self.tab_9)
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.frame_37 = QtGui.QFrame(self.tab_12)
        self.frame_37.setGeometry(QtCore.QRect(0, 10, 231, 191))
        self.frame_37.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_37.setObjectName(_fromUtf8("frame_37"))
        self.checkBox_53 = QtGui.QCheckBox(self.frame_37)
        self.checkBox_53.setGeometry(QtCore.QRect(10, 30, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.comboBox_24 = QtGui.QComboBox(self.frame_37)
        self.comboBox_24.setGeometry(QtCore.QRect(150, 30, 71, 20))
        self.comboBox_24.setObjectName(_fromUtf8("comboBox_24"))
        self.frame_36 = QtGui.QFrame(self.tab_12)
        self.frame_36.setGeometry(QtCore.QRect(10, 230, 231, 41))
        self.frame_36.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_36.setObjectName(_fromUtf8("frame_36"))
        self.dataopCorrOkBtn = QtGui.QPushButton(self.frame_36)
        self.dataopCorrOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.dataopCorrOkBtn.setObjectName(_fromUtf8("dataopCorrOkBtn"))
        self.dataopCorrCancelBtn = QtGui.QPushButton(self.frame_36)
        self.dataopCorrCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.dataopCorrCancelBtn.setObjectName(_fromUtf8("dataopCorrCancelBtn"))
        self.tabWidget_5.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.frame_44 = QtGui.QFrame(self.tab_13)
        self.frame_44.setGeometry(QtCore.QRect(10, 90, 231, 21))
        self.frame_44.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_44.setObjectName(_fromUtf8("frame_44"))
        self.label_95 = QtGui.QLabel(self.frame_44)
        self.label_95.setGeometry(QtCore.QRect(10, 0, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.frame_44)
        self.label_96.setGeometry(QtCore.QRect(130, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_96.setFont(font)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.frame_44)
        self.label_97.setGeometry(QtCore.QRect(190, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.frame_42 = QtGui.QFrame(self.tab_13)
        self.frame_42.setGeometry(QtCore.QRect(10, 210, 231, 51))
        self.frame_42.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_42.setObjectName(_fromUtf8("frame_42"))
        self.label_89 = QtGui.QLabel(self.frame_42)
        self.label_89.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.frame_42)
        self.label_90.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.lineEdit_38 = QtGui.QLineEdit(self.frame_42)
        self.lineEdit_38.setGeometry(QtCore.QRect(90, 30, 101, 16))
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.toolButton_19 = QtGui.QToolButton(self.frame_42)
        self.toolButton_19.setGeometry(QtCore.QRect(200, 30, 21, 16))
        self.toolButton_19.setObjectName(_fromUtf8("toolButton_19"))
        self.comboBox_28 = QtGui.QComboBox(self.frame_42)
        self.comboBox_28.setGeometry(QtCore.QRect(90, 10, 131, 16))
        self.comboBox_28.setObjectName(_fromUtf8("comboBox_28"))
        self.frame_45 = QtGui.QFrame(self.tab_13)
        self.frame_45.setGeometry(QtCore.QRect(10, 10, 231, 71))
        self.frame_45.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_45.setObjectName(_fromUtf8("frame_45"))
        self.label_98 = QtGui.QLabel(self.frame_45)
        self.label_98.setGeometry(QtCore.QRect(10, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_98.setFont(font)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.frame_45)
        self.label_99.setGeometry(QtCore.QRect(10, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.lineEdit_39 = QtGui.QLineEdit(self.frame_45)
        self.lineEdit_39.setGeometry(QtCore.QRect(50, 10, 141, 21))
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.toolButton_20 = QtGui.QToolButton(self.frame_45)
        self.toolButton_20.setGeometry(QtCore.QRect(200, 10, 21, 21))
        self.toolButton_20.setObjectName(_fromUtf8("toolButton_20"))
        self.lineEdit_40 = QtGui.QLineEdit(self.frame_45)
        self.lineEdit_40.setGeometry(QtCore.QRect(50, 40, 171, 21))
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.frame_43 = QtGui.QFrame(self.tab_13)
        self.frame_43.setGeometry(QtCore.QRect(10, 120, 231, 81))
        self.frame_43.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_43.setObjectName(_fromUtf8("frame_43"))
        self.label_91 = QtGui.QLabel(self.frame_43)
        self.label_91.setGeometry(QtCore.QRect(10, 30, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.checkBox_67 = QtGui.QCheckBox(self.frame_43)
        self.checkBox_67.setGeometry(QtCore.QRect(140, 30, 31, 26))
        self.checkBox_67.setText(_fromUtf8(""))
        self.checkBox_67.setObjectName(_fromUtf8("checkBox_67"))
        self.checkBox_68 = QtGui.QCheckBox(self.frame_43)
        self.checkBox_68.setGeometry(QtCore.QRect(190, 30, 31, 26))
        self.checkBox_68.setText(_fromUtf8(""))
        self.checkBox_68.setObjectName(_fromUtf8("checkBox_68"))
        self.dataGraphCorrOkBtn = QtGui.QPushButton(self.tab_13)
        self.dataGraphCorrOkBtn.setGeometry(QtCore.QRect(60, 270, 71, 21))
        self.dataGraphCorrOkBtn.setObjectName(_fromUtf8("dataGraphCorrOkBtn"))
        self.dataGraphCorrCancelBtn = QtGui.QPushButton(self.tab_13)
        self.dataGraphCorrCancelBtn.setGeometry(QtCore.QRect(140, 270, 71, 21))
        self.dataGraphCorrCancelBtn.setObjectName(_fromUtf8("dataGraphCorrCancelBtn"))
        self.tabWidget_5.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.label_17 = QtGui.QLabel(self.tab_14)
        self.label_17.setGeometry(QtCore.QRect(140, 100, 58, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.frame_46 = QtGui.QFrame(self.tab_14)
        self.frame_46.setGeometry(QtCore.QRect(10, 20, 231, 71))
        self.frame_46.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_46.setObjectName(_fromUtf8("frame_46"))
        self.label_18 = QtGui.QLabel(self.frame_46)
        self.label_18.setGeometry(QtCore.QRect(20, 10, 22, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_46)
        self.lineEdit_9.setGeometry(QtCore.QRect(50, 10, 133, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.toolButton_4 = QtGui.QToolButton(self.frame_46)
        self.toolButton_4.setGeometry(QtCore.QRect(190, 10, 25, 19))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.label_19 = QtGui.QLabel(self.frame_46)
        self.label_19.setGeometry(QtCore.QRect(20, 40, 24, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_46)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 40, 171, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.frame_50 = QtGui.QFrame(self.tab_14)
        self.frame_50.setGeometry(QtCore.QRect(10, 140, 231, 41))
        self.frame_50.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_50.setObjectName(_fromUtf8("frame_50"))
        self.datasaveCorrOkBtn = QtGui.QPushButton(self.frame_50)
        self.datasaveCorrOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.datasaveCorrOkBtn.setObjectName(_fromUtf8("datasaveCorrOkBtn"))
        self.dataSaveCorrCancelBtn = QtGui.QPushButton(self.frame_50)
        self.dataSaveCorrCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.dataSaveCorrCancelBtn.setObjectName(_fromUtf8("dataSaveCorrCancelBtn"))
        self.tabWidget_5.addTab(self.tab_14, _fromUtf8(""))
        self.gridLayout_12.addWidget(self.tabWidget_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.frame_12 = QtGui.QFrame(self.centralWidget)
        self.frame_12.setGeometry(QtCore.QRect(260, 380, 301, 131))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.tabWidget_2 = QtGui.QTabWidget(self.frame_12)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 111))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textEdit = Qsci.QsciScintilla(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 261, 61))
        self.textEdit.setToolTip(_fromUtf8(""))
        self.textEdit.setWhatsThis(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 854, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFILE = QtGui.QMenu(self.menuBar)
        self.menuFILE.setObjectName(_fromUtf8("menuFILE"))
        self.menuRUN = QtGui.QMenu(self.menuBar)
        self.menuRUN.setObjectName(_fromUtf8("menuRUN"))
        self.menuOPTIONS = QtGui.QMenu(self.menuBar)
        self.menuOPTIONS.setObjectName(_fromUtf8("menuOPTIONS"))
        self.menuHELP = QtGui.QMenu(self.menuBar)
        self.menuHELP.setObjectName(_fromUtf8("menuHELP"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionabrirObj = QtGui.QAction(MainWindow)
        self.actionabrirObj.setObjectName(_fromUtf8("actionabrirObj"))
        self.actioncrearObj = QtGui.QAction(MainWindow)
        self.actioncrearObj.setObjectName(_fromUtf8("actioncrearObj"))
        self.actionguardarObj = QtGui.QAction(MainWindow)
        self.actionguardarObj.setObjectName(_fromUtf8("actionguardarObj"))
        self.actionStartObj = QtGui.QAction(MainWindow)
        self.actionStartObj.setObjectName(_fromUtf8("actionStartObj"))
        self.actionPausaObj = QtGui.QAction(MainWindow)
        self.actionPausaObj.setObjectName(_fromUtf8("actionPausaObj"))
        self.actionconfigLogfileObj = QtGui.QAction(MainWindow)
        self.actionconfigLogfileObj.setObjectName(_fromUtf8("actionconfigLogfileObj"))
        self.actionconfigserverObj = QtGui.QAction(MainWindow)
        self.actionconfigserverObj.setObjectName(_fromUtf8("actionconfigserverObj"))
        self.actionAboutObj = QtGui.QAction(MainWindow)
        self.actionAboutObj.setObjectName(_fromUtf8("actionAboutObj"))
        self.actionPrfObj = QtGui.QAction(MainWindow)
        self.actionPrfObj.setObjectName(_fromUtf8("actionPrfObj"))
        self.actionOpenObj = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Downloads/IMAGENES/Open Sign.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenObj.setIcon(icon)
        self.actionOpenObj.setObjectName(_fromUtf8("actionOpenObj"))
        self.actionsaveObj = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Downloads/IMAGENES/guardar.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsaveObj.setIcon(icon1)
        self.actionsaveObj.setObjectName(_fromUtf8("actionsaveObj"))
        self.actionPlayObj = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Downloads/IMAGENES/play.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayObj.setIcon(icon2)
        self.actionPlayObj.setObjectName(_fromUtf8("actionPlayObj"))
        self.actionstopObj = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Downloads/IMAGENES/stop.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstopObj.setIcon(icon3)
        self.actionstopObj.setObjectName(_fromUtf8("actionstopObj"))
        self.actioncreateObj = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Downloads/IMAGENES/Crear.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncreateObj.setIcon(icon4)
        self.actioncreateObj.setObjectName(_fromUtf8("actioncreateObj"))
        self.actionCerrarObj = QtGui.QAction(MainWindow)
        self.actionCerrarObj.setObjectName(_fromUtf8("actionCerrarObj"))
        self.menuFILE.addAction(self.actionabrirObj)
        self.menuFILE.addAction(self.actioncrearObj)
        self.menuFILE.addAction(self.actionguardarObj)
        self.menuFILE.addAction(self.actionCerrarObj)
        self.menuRUN.addAction(self.actionStartObj)
        self.menuRUN.addAction(self.actionPausaObj)
        self.menuOPTIONS.addAction(self.actionconfigLogfileObj)
        self.menuOPTIONS.addAction(self.actionconfigserverObj)
        self.menuHELP.addAction(self.actionAboutObj)
        self.menuHELP.addAction(self.actionPrfObj)
        self.menuBar.addAction(self.menuFILE.menuAction())
        self.menuBar.addAction(self.menuRUN.menuAction())
        self.menuBar.addAction(self.menuOPTIONS.menuAction())
        self.menuBar.addAction(self.menuHELP.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpenObj)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actioncreateObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsaveObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlayObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionstopObj)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
 #++++++++++++++++++NEW PROPERTIES+++++++++++++++++#
        QtGui.QToolTip.setFont(QtGui.QFont('SansSerif', 10))
        self.addpBtn.setToolTip('Add_New_Project')    
        self.addUnitProces.setToolTip('Add_New_Unit_Process')  

  #++++++++++++++++++NEW PROPERTIES+++++++++++++++++#
        self.model = QtGui.QStandardItemModel()
        self.treeView.setModel(self.model)
        self.treeView.clicked.connect(self.clickFunctiontree)
        self.treeView.expandAll()
        #self.treeView.clicked.connect(self.treefunction1)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Project Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Project Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.addpBtn.setText(QtGui.QApplication.translate("MainWindow", "PROJECT", None, QtGui.QApplication.UnicodeUTF8))
        self.addUnitProces.setText(QtGui.QApplication.translate("MainWindow", "UNIT PROCESS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Read Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.readModeCmBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "OffLine", None, QtGui.QApplication.UnicodeUTF8))
        self.readModeCmBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "OnLine", None, QtGui.QApplication.UnicodeUTF8))
        self.dataWaitLine.setText(QtGui.QApplication.translate("MainWindow", "Wait(sec):", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeLine.setText(QtGui.QApplication.translate("MainWindow", "Data type :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathline.setText(QtGui.QApplication.translate("MainWindow", "Data Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeCmbBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeCmbBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOperationModeline.setText(QtGui.QApplication.translate("MainWindow", "Project Configuration:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataStartLine.setText(QtGui.QApplication.translate("MainWindow", "Start date :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataEndline.setText(QtGui.QApplication.translate("MainWindow", "End date :", None, QtGui.QApplication.UnicodeUTF8))
        self.LTReferenceRdBtn.setText(QtGui.QApplication.translate("MainWindow", "Local time frame of reference", None, QtGui.QApplication.UnicodeUTF8))
        self.dataInitialTimeLine.setText(QtGui.QApplication.translate("MainWindow", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.dataFinelTimeLine.setText(QtGui.QApplication.translate("MainWindow", "Final Time", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.removeDCCEB.setText(QtGui.QApplication.translate("MainWindow", "Remove DC", None, QtGui.QApplication.UnicodeUTF8))
        self.coherentIntegrationCEB.setText(QtGui.QApplication.translate("MainWindow", "Coherent Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.decodeCEB.setText(QtGui.QApplication.translate("MainWindow", "Decodification", None, QtGui.QApplication.UnicodeUTF8))
        self.profileOpVolcob.setItemText(0, QtGui.QApplication.translate("MainWindow", "ProfileList", None, QtGui.QApplication.UnicodeUTF8))
        self.profileOpVolcob.setItemText(1, QtGui.QApplication.translate("MainWindow", "ProfileRangeList", None, QtGui.QApplication.UnicodeUTF8))
        self.selecChannelopVolCEB.setText(QtGui.QApplication.translate("MainWindow", "Select Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.selecHeighopVolCEB.setText(QtGui.QApplication.translate("MainWindow", "Select Heights", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.datalabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPotlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Potencia", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPrefixlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphicsVolPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathlabelOutVol.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOutVolPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataSufixlabelOutVol.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_49.setText(QtGui.QApplication.translate("MainWindow", "Remove DC", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_50.setText(QtGui.QApplication.translate("MainWindow", "Remove Interference", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_51.setText(QtGui.QApplication.translate("MainWindow", "Integration Incoherent", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_52.setText(QtGui.QApplication.translate("MainWindow", "Operation 4", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_83.setText(QtGui.QApplication.translate("MainWindow", "RTI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_84.setText(QtGui.QApplication.translate("MainWindow", "CROSS-CORRELATION+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_85.setText(QtGui.QApplication.translate("MainWindow", "CROSS-SPECTRA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_86.setText(QtGui.QApplication.translate("MainWindow", "NOISE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_100.setText(QtGui.QApplication.translate("MainWindow", "PHASE", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_17.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_18.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Data format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_53.setText(QtGui.QApplication.translate("MainWindow", "Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_19.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_98.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_99.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_20.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setText(QtGui.QApplication.translate("MainWindow", "POTENCIA", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Data format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataSaveCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Ouput Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFILE.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRUN.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOPTIONS.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHELP.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar_2.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar_2", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionabrirObj.setText(QtGui.QApplication.translate("MainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actioncrearObj.setText(QtGui.QApplication.translate("MainWindow", "Crear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionguardarObj.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStartObj.setText(QtGui.QApplication.translate("MainWindow", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPausaObj.setText(QtGui.QApplication.translate("MainWindow", "pausa", None, QtGui.QApplication.UnicodeUTF8))
        self.actionconfigLogfileObj.setText(QtGui.QApplication.translate("MainWindow", "configLogfileObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionconfigserverObj.setText(QtGui.QApplication.translate("MainWindow", "configServerFTP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutObj.setText(QtGui.QApplication.translate("MainWindow", "aboutObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrfObj.setText(QtGui.QApplication.translate("MainWindow", "prfObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenObj.setText(QtGui.QApplication.translate("MainWindow", "openObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenObj.setToolTip(QtGui.QApplication.translate("MainWindow", "open file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsaveObj.setText(QtGui.QApplication.translate("MainWindow", "saveObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionsaveObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayObj.setText(QtGui.QApplication.translate("MainWindow", "playObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlayObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actionstopObj.setText(QtGui.QApplication.translate("MainWindow", "stopObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionstopObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actioncreateObj.setText(QtGui.QApplication.translate("MainWindow", "createObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actioncreateObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCerrarObj.setText(QtGui.QApplication.translate("MainWindow", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

