# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alex\ericworkspace\UIDOS\MainWindow_january.ui'
#
# Created: Wed Jan 16 08:40:57 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(867, 589)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(580, 0, 281, 531))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 261, 31))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_46 = QtGui.QLabel(self.frame_6)
        self.label_46.setGeometry(QtCore.QRect(70, 0, 125, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.treeView_2 = QtGui.QTreeView(self.frame_2)
        self.treeView_2.setGeometry(QtCore.QRect(10, 50, 261, 471))
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 251, 531))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_9 = QtGui.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 231, 61))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label = QtGui.QLabel(self.frame_9)
        self.label.setGeometry(QtCore.QRect(60, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.addprojectBtn = QtGui.QPushButton(self.frame_9)
        self.addprojectBtn.setGeometry(QtCore.QRect(10, 30, 101, 23))
        self.addprojectBtn.setObjectName(_fromUtf8("addprojectBtn"))
        self.addUnitProces = QtGui.QPushButton(self.frame_9)
        self.addUnitProces.setGeometry(QtCore.QRect(120, 30, 101, 23))
        self.addUnitProces.setObjectName(_fromUtf8("addUnitProces"))
        self.treeView = QtGui.QTreeView(self.frame)
        self.treeView.setGeometry(QtCore.QRect(10, 80, 231, 441))
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.frame_7 = QtGui.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(250, 0, 331, 531))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.tabWidgetProject = QtGui.QTabWidget(self.frame_7)
        self.tabWidgetProject.setEnabled(True)
        self.tabWidgetProject.setGeometry(QtCore.QRect(10, 10, 311, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetProject.setFont(font)
        self.tabWidgetProject.setObjectName(_fromUtf8("tabWidgetProject"))
        self.tabProject = QtGui.QWidget()
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.frame_5 = QtGui.QFrame(self.tabProject)
        self.frame_5.setGeometry(QtCore.QRect(10, 140, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_55 = QtGui.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.readModeCmBox = QtGui.QComboBox(self.frame_5)
        self.readModeCmBox.setGeometry(QtCore.QRect(100, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.readModeCmBox.setFont(font)
        self.readModeCmBox.setObjectName(_fromUtf8("readModeCmBox"))
        self.readModeCmBox.addItem(_fromUtf8(""))
        self.readModeCmBox.addItem(_fromUtf8(""))
        self.dataWaitLine = QtGui.QLabel(self.frame_5)
        self.dataWaitLine.setGeometry(QtCore.QRect(180, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataWaitLine.setFont(font)
        self.dataWaitLine.setObjectName(_fromUtf8("dataWaitLine"))
        self.dataWaitTxt = QtGui.QLineEdit(self.frame_5)
        self.dataWaitTxt.setGeometry(QtCore.QRect(250, 10, 31, 16))
        self.dataWaitTxt.setObjectName(_fromUtf8("dataWaitTxt"))
        self.frame_4 = QtGui.QFrame(self.tabProject)
        self.frame_4.setGeometry(QtCore.QRect(10, 60, 291, 71))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.dataTypeLine = QtGui.QLabel(self.frame_4)
        self.dataTypeLine.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataTypeLine.setFont(font)
        self.dataTypeLine.setObjectName(_fromUtf8("dataTypeLine"))
        self.dataPathline = QtGui.QLabel(self.frame_4)
        self.dataPathline.setGeometry(QtCore.QRect(10, 40, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataPathline.setFont(font)
        self.dataPathline.setObjectName(_fromUtf8("dataPathline"))
        self.dataTypeCmbBox = QtGui.QComboBox(self.frame_4)
        self.dataTypeCmbBox.setGeometry(QtCore.QRect(90, 10, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataTypeCmbBox.setFont(font)
        self.dataTypeCmbBox.setObjectName(_fromUtf8("dataTypeCmbBox"))
        self.dataTypeCmbBox.addItem(_fromUtf8(""))
        self.dataTypeCmbBox.addItem(_fromUtf8(""))
        self.dataPathTxt = QtGui.QLineEdit(self.frame_4)
        self.dataPathTxt.setGeometry(QtCore.QRect(90, 40, 161, 21))
        self.dataPathTxt.setObjectName(_fromUtf8("dataPathTxt"))
        self.dataPathBrowse = QtGui.QPushButton(self.frame_4)
        self.dataPathBrowse.setGeometry(QtCore.QRect(260, 40, 21, 20))
        self.dataPathBrowse.setObjectName(_fromUtf8("dataPathBrowse"))
        self.dataFormatTxt = QtGui.QLineEdit(self.frame_4)
        self.dataFormatTxt.setGeometry(QtCore.QRect(250, 10, 31, 21))
        self.dataFormatTxt.setObjectName(_fromUtf8("dataFormatTxt"))
        self.frame_3 = QtGui.QFrame(self.tabProject)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 291, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.dataOperationModeline = QtGui.QLabel(self.frame_3)
        self.dataOperationModeline.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataOperationModeline.setFont(font)
        self.dataOperationModeline.setObjectName(_fromUtf8("dataOperationModeline"))
        self.nameProjectTxt = QtGui.QLineEdit(self.frame_3)
        self.nameProjectTxt.setGeometry(QtCore.QRect(120, 10, 161, 21))
        self.nameProjectTxt.setObjectName(_fromUtf8("nameProjectTxt"))
        self.frame_8 = QtGui.QFrame(self.tabProject)
        self.frame_8.setGeometry(QtCore.QRect(10, 180, 291, 71))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.dataStartLine = QtGui.QLabel(self.frame_8)
        self.dataStartLine.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataStartLine.setFont(font)
        self.dataStartLine.setObjectName(_fromUtf8("dataStartLine"))
        self.dataEndline = QtGui.QLabel(self.frame_8)
        self.dataEndline.setGeometry(QtCore.QRect(20, 30, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataEndline.setFont(font)
        self.dataEndline.setObjectName(_fromUtf8("dataEndline"))
        self.starDateCmbBox = QtGui.QComboBox(self.frame_8)
        self.starDateCmbBox.setGeometry(QtCore.QRect(100, 10, 171, 16))
        self.starDateCmbBox.setObjectName(_fromUtf8("starDateCmbBox"))
        self.endDateCmbBox = QtGui.QComboBox(self.frame_8)
        self.endDateCmbBox.setGeometry(QtCore.QRect(100, 30, 171, 16))
        self.endDateCmbBox.setObjectName(_fromUtf8("endDateCmbBox"))
        self.LTReferenceRdBtn = QtGui.QRadioButton(self.frame_8)
        self.LTReferenceRdBtn.setGeometry(QtCore.QRect(40, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.LTReferenceRdBtn.setFont(font)
        self.LTReferenceRdBtn.setObjectName(_fromUtf8("LTReferenceRdBtn"))
        self.dataOkBtn = QtGui.QPushButton(self.tabProject)
        self.dataOkBtn.setGeometry(QtCore.QRect(70, 340, 81, 21))
        self.dataOkBtn.setObjectName(_fromUtf8("dataOkBtn"))
        self.dataCancelBtn = QtGui.QPushButton(self.tabProject)
        self.dataCancelBtn.setGeometry(QtCore.QRect(170, 340, 81, 21))
        self.dataCancelBtn.setObjectName(_fromUtf8("dataCancelBtn"))
        self.frame_10 = QtGui.QFrame(self.tabProject)
        self.frame_10.setGeometry(QtCore.QRect(10, 260, 291, 71))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.dataInitialTimeLine = QtGui.QLabel(self.frame_10)
        self.dataInitialTimeLine.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataInitialTimeLine.setFont(font)
        self.dataInitialTimeLine.setObjectName(_fromUtf8("dataInitialTimeLine"))
        self.dataFinelTimeLine = QtGui.QLabel(self.frame_10)
        self.dataFinelTimeLine.setGeometry(QtCore.QRect(20, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataFinelTimeLine.setFont(font)
        self.dataFinelTimeLine.setObjectName(_fromUtf8("dataFinelTimeLine"))
        
        #------------QTIME EDIT-----------#     
        self.startTimeEdit = QtGui.QTimeEdit(self.frame_10)
        self.startTimeEdit.setDisplayFormat("hh:mm:ss")
        self.time =QtCore.QTime()
        self.hour =0
        self.min  =0
        self.sec  =0
        
        self.startTimeEdit.setGeometry(QtCore.QRect(150, 10, 121, 20))
        self.startTimeEdit.setObjectName(_fromUtf8("startTimeEdit"))
        
        
         #------------QTIME EDIT-----------#
        self.timeEdit_2 = QtGui.QTimeEdit(self.frame_10)
        self.timeEdit_2.setDisplayFormat("hh:mm:ss")
        self.timeEdit_2.setGeometry(QtCore.QRect(150, 40, 121, 20))
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        
      
        self.tabWidgetProject.addTab(self.tabProject, _fromUtf8(""))
        self.tabVoltage = QtGui.QWidget()
        self.tabVoltage.setEnabled(True)
        self.tabVoltage.setObjectName(_fromUtf8("tabVoltage"))
        self.tabWidgetVol = QtGui.QTabWidget(self.tabVoltage)
        self.tabWidgetVol.setEnabled(True)
        self.tabWidgetVol.setGeometry(QtCore.QRect(10, 10, 291, 341))
        self.tabWidgetVol.setObjectName(_fromUtf8("tabWidgetVol"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.selecChannelopVolCEB = QtGui.QCheckBox(self.tab_3)
        self.selecChannelopVolCEB.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.selecChannelopVolCEB.setObjectName(_fromUtf8("selecChannelopVolCEB"))
        self.numberChannelopVol = QtGui.QLineEdit(self.tab_3)
        self.numberChannelopVol.setEnabled(True)
        self.numberChannelopVol.setGeometry(QtCore.QRect(170, 10, 91, 20))
        self.numberChannelopVol.setObjectName(_fromUtf8("numberChannelopVol"))
        self.selecHeighopVolCEB = QtGui.QCheckBox(self.tab_3)
        self.selecHeighopVolCEB.setGeometry(QtCore.QRect(10, 40, 121, 21))
        self.selecHeighopVolCEB.setObjectName(_fromUtf8("selecHeighopVolCEB"))
        self.filterCEB = QtGui.QCheckBox(self.tab_3)
        self.filterCEB.setGeometry(QtCore.QRect(10, 70, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filterCEB.setFont(font)
        self.filterCEB.setObjectName(_fromUtf8("filterCEB"))
        self.profileSelecopVolCEB = QtGui.QCheckBox(self.tab_3)
        self.profileSelecopVolCEB.setGeometry(QtCore.QRect(10, 100, 111, 17))
        self.profileSelecopVolCEB.setObjectName(_fromUtf8("profileSelecopVolCEB"))
        self.decodeCEB = QtGui.QCheckBox(self.tab_3)
        self.decodeCEB.setGeometry(QtCore.QRect(10, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.decodeCEB.setFont(font)
        self.decodeCEB.setObjectName(_fromUtf8("decodeCEB"))
        self.coherentIntegrationCEB = QtGui.QCheckBox(self.tab_3)
        self.coherentIntegrationCEB.setGeometry(QtCore.QRect(10, 160, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.coherentIntegrationCEB.setFont(font)
        self.coherentIntegrationCEB.setObjectName(_fromUtf8("coherentIntegrationCEB"))
        self.lineHeighProfileTxtopVol = QtGui.QLineEdit(self.tab_3)
        self.lineHeighProfileTxtopVol.setGeometry(QtCore.QRect(170, 40, 91, 20))
        self.lineHeighProfileTxtopVol.setObjectName(_fromUtf8("lineHeighProfileTxtopVol"))
        self.filtercob = QtGui.QComboBox(self.tab_3)
        self.filtercob.setGeometry(QtCore.QRect(170, 70, 91, 20))
        self.filtercob.setObjectName(_fromUtf8("filtercob"))
        self.lineProfileSelecopVolCEB = QtGui.QLineEdit(self.tab_3)
        self.lineProfileSelecopVolCEB.setGeometry(QtCore.QRect(170, 100, 91, 20))
        self.lineProfileSelecopVolCEB.setObjectName(_fromUtf8("lineProfileSelecopVolCEB"))
        self.decodeCcob = QtGui.QComboBox(self.tab_3)
        self.decodeCcob.setGeometry(QtCore.QRect(170, 130, 91, 20))
        self.decodeCcob.setObjectName(_fromUtf8("decodeCcob"))
        self.numberIntegration = QtGui.QLineEdit(self.tab_3)
        self.numberIntegration.setGeometry(QtCore.QRect(170, 160, 91, 21))
        self.numberIntegration.setObjectName(_fromUtf8("numberIntegration"))
        self.dataopVolOkBtn = QtGui.QPushButton(self.tab_3)
        self.dataopVolOkBtn.setGeometry(QtCore.QRect(60, 210, 71, 21))
        self.dataopVolOkBtn.setObjectName(_fromUtf8("dataopVolOkBtn"))
        self.dataopVolCancelBtn = QtGui.QPushButton(self.tab_3)
        self.dataopVolCancelBtn.setGeometry(QtCore.QRect(150, 210, 71, 21))
        self.dataopVolCancelBtn.setObjectName(_fromUtf8("dataopVolCancelBtn"))
        self.tabWidgetVol.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_17 = QtGui.QFrame(self.tab_2)
        self.frame_17.setGeometry(QtCore.QRect(10, 100, 251, 71))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_17.setObjectName(_fromUtf8("frame_17"))
        self.datalabelGraphicsVol = QtGui.QLabel(self.frame_17)
        self.datalabelGraphicsVol.setGeometry(QtCore.QRect(10, 10, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datalabelGraphicsVol.setFont(font)
        self.datalabelGraphicsVol.setObjectName(_fromUtf8("datalabelGraphicsVol"))
        self.dataPotlabelGraphicsVol = QtGui.QLabel(self.frame_17)
        self.dataPotlabelGraphicsVol.setGeometry(QtCore.QRect(10, 30, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPotlabelGraphicsVol.setFont(font)
        self.dataPotlabelGraphicsVol.setObjectName(_fromUtf8("dataPotlabelGraphicsVol"))
        self.showdataGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.showdataGraphicsVol.setGeometry(QtCore.QRect(140, 10, 31, 26))
        self.showdataGraphicsVol.setText(_fromUtf8(""))
        self.showdataGraphicsVol.setObjectName(_fromUtf8("showdataGraphicsVol"))
        self.savedataCEBGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.savedataCEBGraphicsVol.setGeometry(QtCore.QRect(200, 10, 31, 26))
        self.savedataCEBGraphicsVol.setText(_fromUtf8(""))
        self.savedataCEBGraphicsVol.setObjectName(_fromUtf8("savedataCEBGraphicsVol"))
        self.showPotCEBGraphicsVol = QtGui.QCheckBox(self.frame_17)
        self.showPotCEBGraphicsVol.setGeometry(QtCore.QRect(140, 30, 31, 26))
        self.showPotCEBGraphicsVol.setText(_fromUtf8(""))
        self.showPotCEBGraphicsVol.setObjectName(_fromUtf8("showPotCEBGraphicsVol"))
        self.checkBox_18 = QtGui.QCheckBox(self.frame_17)
        self.checkBox_18.setGeometry(QtCore.QRect(200, 30, 31, 26))
        self.checkBox_18.setText(_fromUtf8(""))
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.frame_19 = QtGui.QFrame(self.tab_2)
        self.frame_19.setGeometry(QtCore.QRect(10, 190, 251, 61))
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_19.setObjectName(_fromUtf8("frame_19"))
        self.label_13 = QtGui.QLabel(self.frame_19)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_19)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_19)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 30, 101, 21))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.toolButton_2 = QtGui.QToolButton(self.frame_19)
        self.toolButton_2.setGeometry(QtCore.QRect(210, 30, 31, 21))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.comboBox_10 = QtGui.QComboBox(self.frame_19)
        self.comboBox_10.setGeometry(QtCore.QRect(90, 10, 151, 16))
        self.comboBox_10.setObjectName(_fromUtf8("comboBox_10"))
        self.dataGraphVolOkBtn = QtGui.QPushButton(self.tab_2)
        self.dataGraphVolOkBtn.setGeometry(QtCore.QRect(70, 270, 71, 21))
        self.dataGraphVolOkBtn.setObjectName(_fromUtf8("dataGraphVolOkBtn"))
        self.dataGraphVolCancelBtn = QtGui.QPushButton(self.tab_2)
        self.dataGraphVolCancelBtn.setGeometry(QtCore.QRect(150, 270, 71, 21))
        self.dataGraphVolCancelBtn.setObjectName(_fromUtf8("dataGraphVolCancelBtn"))
        self.dataPathlabelGraphicsVol = QtGui.QLabel(self.tab_2)
        self.dataPathlabelGraphicsVol.setGeometry(QtCore.QRect(20, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPathlabelGraphicsVol.setFont(font)
        self.dataPathlabelGraphicsVol.setObjectName(_fromUtf8("dataPathlabelGraphicsVol"))
        self.dataPrefixlabelGraphicsVol = QtGui.QLabel(self.tab_2)
        self.dataPrefixlabelGraphicsVol.setGeometry(QtCore.QRect(20, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataPrefixlabelGraphicsVol.setFont(font)
        self.dataPrefixlabelGraphicsVol.setObjectName(_fromUtf8("dataPrefixlabelGraphicsVol"))
        self.dataPathtxtGraphicsVol = QtGui.QLineEdit(self.tab_2)
        self.dataPathtxtGraphicsVol.setGeometry(QtCore.QRect(70, 10, 161, 21))
        self.dataPathtxtGraphicsVol.setObjectName(_fromUtf8("dataPathtxtGraphicsVol"))
        self.dataPrefixtxtGraphicsVol = QtGui.QLineEdit(self.tab_2)
        self.dataPrefixtxtGraphicsVol.setGeometry(QtCore.QRect(70, 40, 191, 21))
        self.dataPrefixtxtGraphicsVol.setObjectName(_fromUtf8("dataPrefixtxtGraphicsVol"))
        self.dataGraphicsVolPathBrowse = QtGui.QToolButton(self.tab_2)
        self.dataGraphicsVolPathBrowse.setGeometry(QtCore.QRect(240, 10, 21, 21))
        self.dataGraphicsVolPathBrowse.setObjectName(_fromUtf8("dataGraphicsVolPathBrowse"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(130, 80, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(200, 80, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.tabWidgetVol.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.frame_15 = QtGui.QFrame(self.tab_4)
        self.frame_15.setGeometry(QtCore.QRect(10, 20, 251, 71))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.dataPathlabelOutVol = QtGui.QLabel(self.frame_15)
        self.dataPathlabelOutVol.setGeometry(QtCore.QRect(20, 10, 31, 16))
        self.dataPathlabelOutVol.setObjectName(_fromUtf8("dataPathlabelOutVol"))
        self.dataPathtxtOutVol = QtGui.QLineEdit(self.frame_15)
        self.dataPathtxtOutVol.setGeometry(QtCore.QRect(62, 10, 131, 20))
        self.dataPathtxtOutVol.setObjectName(_fromUtf8("dataPathtxtOutVol"))
        self.dataOutVolPathBrowse = QtGui.QToolButton(self.frame_15)
        self.dataOutVolPathBrowse.setGeometry(QtCore.QRect(210, 10, 25, 19))
        self.dataOutVolPathBrowse.setObjectName(_fromUtf8("dataOutVolPathBrowse"))
        self.dataSufixlabelOutVol = QtGui.QLabel(self.frame_15)
        self.dataSufixlabelOutVol.setGeometry(QtCore.QRect(20, 40, 41, 16))
        self.dataSufixlabelOutVol.setObjectName(_fromUtf8("dataSufixlabelOutVol"))
        self.dataSufixtxtOutVol = QtGui.QLineEdit(self.frame_15)
        self.dataSufixtxtOutVol.setGeometry(QtCore.QRect(60, 40, 171, 20))
        self.dataSufixtxtOutVol.setObjectName(_fromUtf8("dataSufixtxtOutVol"))
        self.datasaveVolOkBtn = QtGui.QPushButton(self.tab_4)
        self.datasaveVolOkBtn.setGeometry(QtCore.QRect(60, 120, 71, 21))
        self.datasaveVolOkBtn.setObjectName(_fromUtf8("datasaveVolOkBtn"))
        self.datasaveVolCancelBtn = QtGui.QPushButton(self.tab_4)
        self.datasaveVolCancelBtn.setGeometry(QtCore.QRect(150, 120, 71, 21))
        self.datasaveVolCancelBtn.setObjectName(_fromUtf8("datasaveVolCancelBtn"))
        self.tabWidgetVol.addTab(self.tab_4, _fromUtf8(""))
        self.tabWidgetProject.addTab(self.tabVoltage, _fromUtf8(""))
        self.tabSpectra = QtGui.QWidget()
        self.tabSpectra.setObjectName(_fromUtf8("tabSpectra"))
        self.tabWidgetSpec = QtGui.QTabWidget(self.tabSpectra)
        self.tabWidgetSpec.setEnabled(True)
        self.tabWidgetSpec.setGeometry(QtCore.QRect(10, 10, 291, 341))
        self.tabWidgetSpec.setObjectName(_fromUtf8("tabWidgetSpec"))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.nFFTPointOpSpecCEB = QtGui.QCheckBox(self.tab_8)
        self.nFFTPointOpSpecCEB.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.nFFTPointOpSpecCEB.setObjectName(_fromUtf8("nFFTPointOpSpecCEB"))
        self.selecChannelopSpecCEB = QtGui.QCheckBox(self.tab_8)
        self.selecChannelopSpecCEB.setGeometry(QtCore.QRect(10, 40, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selecChannelopSpecCEB.setFont(font)
        self.selecChannelopSpecCEB.setObjectName(_fromUtf8("selecChannelopSpecCEB"))
        self.IncohIntOpSpecCEB = QtGui.QCheckBox(self.tab_8)
        self.IncohIntOpSpecCEB.setGeometry(QtCore.QRect(10, 70, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IncohIntOpSpecCEB.setFont(font)
        self.IncohIntOpSpecCEB.setObjectName(_fromUtf8("IncohIntOpSpecCEB"))
        self.removedcOpSpecCEB = QtGui.QCheckBox(self.tab_8)
        self.removedcOpSpecCEB.setGeometry(QtCore.QRect(10, 100, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removedcOpSpecCEB.setFont(font)
        self.removedcOpSpecCEB.setObjectName(_fromUtf8("removedcOpSpecCEB"))
        self.removeIntopSpec = QtGui.QCheckBox(self.tab_8)
        self.removeIntopSpec.setGeometry(QtCore.QRect(10, 130, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeIntopSpec.setFont(font)
        self.removeIntopSpec.setObjectName(_fromUtf8("removeIntopSpec"))
        self.valuenFFTPointOpSpec = QtGui.QLineEdit(self.tab_8)
        self.valuenFFTPointOpSpec.setGeometry(QtCore.QRect(200, 10, 71, 20))
        self.valuenFFTPointOpSpec.setObjectName(_fromUtf8("valuenFFTPointOpSpec"))
        self.numberChannelopSpec = QtGui.QLineEdit(self.tab_8)
        self.numberChannelopSpec.setGeometry(QtCore.QRect(200, 40, 71, 20))
        self.numberChannelopSpec.setObjectName(_fromUtf8("numberChannelopSpec"))
        self.valueIncohIntOpSpec = QtGui.QLineEdit(self.tab_8)
        self.valueIncohIntOpSpec.setGeometry(QtCore.QRect(200, 70, 71, 20))
        self.valueIncohIntOpSpec.setObjectName(_fromUtf8("valueIncohIntOpSpec"))
        self.lineEdit_33 = QtGui.QLineEdit(self.tab_8)
        self.lineEdit_33.setGeometry(QtCore.QRect(200, 130, 71, 20))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.dataopSpecOkBtn = QtGui.QPushButton(self.tab_8)
        self.dataopSpecOkBtn.setGeometry(QtCore.QRect(50, 180, 71, 21))
        self.dataopSpecOkBtn.setObjectName(_fromUtf8("dataopSpecOkBtn"))
        self.dataopSpecCancelBtn = QtGui.QPushButton(self.tab_8)
        self.dataopSpecCancelBtn.setGeometry(QtCore.QRect(160, 180, 71, 21))
        self.dataopSpecCancelBtn.setObjectName(_fromUtf8("dataopSpecCancelBtn"))
        self.valueremoveDCOpSpec = QtGui.QLineEdit(self.tab_8)
        self.valueremoveDCOpSpec.setGeometry(QtCore.QRect(200, 100, 71, 20))
        self.valueremoveDCOpSpec.setObjectName(_fromUtf8("valueremoveDCOpSpec"))
        self.tabWidgetSpec.addTab(self.tab_8, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.dataGraphSpecCancelBtn = QtGui.QPushButton(self.tab_10)
        self.dataGraphSpecCancelBtn.setGeometry(QtCore.QRect(150, 280, 71, 21))
        self.dataGraphSpecCancelBtn.setObjectName(_fromUtf8("dataGraphSpecCancelBtn"))
        self.frame_40 = QtGui.QFrame(self.tab_10)
        self.frame_40.setGeometry(QtCore.QRect(10, 50, 261, 161))
        self.frame_40.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_40.setObjectName(_fromUtf8("frame_40"))
        self.RTIPlotGraphLabel = QtGui.QLabel(self.frame_40)
        self.RTIPlotGraphLabel.setGeometry(QtCore.QRect(10, 70, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RTIPlotGraphLabel.setFont(font)
        self.RTIPlotGraphLabel.setObjectName(_fromUtf8("RTIPlotGraphLabel"))
        self.SpectraPlotGraphLabel = QtGui.QLabel(self.frame_40)
        self.SpectraPlotGraphLabel.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.SpectraPlotGraphLabel.setObjectName(_fromUtf8("SpectraPlotGraphLabel"))
        self.NoisePlotGraphLabel = QtGui.QLabel(self.frame_40)
        self.NoisePlotGraphLabel.setGeometry(QtCore.QRect(10, 130, 66, 21))
        self.NoisePlotGraphLabel.setObjectName(_fromUtf8("NoisePlotGraphLabel"))
        self.RTIPlotGraphCEB = QtGui.QCheckBox(self.frame_40)
        self.RTIPlotGraphCEB.setGeometry(QtCore.QRect(150, 70, 31, 26))
        self.RTIPlotGraphCEB.setText(_fromUtf8(""))
        self.RTIPlotGraphCEB.setObjectName(_fromUtf8("RTIPlotGraphCEB"))
        self.checkBox_58 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_58.setGeometry(QtCore.QRect(210, 70, 31, 26))
        self.checkBox_58.setText(_fromUtf8(""))
        self.checkBox_58.setObjectName(_fromUtf8("checkBox_58"))
        self.checkBox_60 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_60.setGeometry(QtCore.QRect(210, 40, 31, 26))
        self.checkBox_60.setText(_fromUtf8(""))
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.CrossSpectraPlotGraphceb = QtGui.QCheckBox(self.frame_40)
        self.CrossSpectraPlotGraphceb.setGeometry(QtCore.QRect(150, 40, 31, 21))
        self.CrossSpectraPlotGraphceb.setText(_fromUtf8(""))
        self.CrossSpectraPlotGraphceb.setObjectName(_fromUtf8("CrossSpectraPlotGraphceb"))
        self.NoisePlotGraphceb = QtGui.QCheckBox(self.frame_40)
        self.NoisePlotGraphceb.setGeometry(QtCore.QRect(150, 130, 20, 26))
        self.NoisePlotGraphceb.setText(_fromUtf8(""))
        self.NoisePlotGraphceb.setObjectName(_fromUtf8("NoisePlotGraphceb"))
        self.checkBox_64 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_64.setGeometry(QtCore.QRect(210, 130, 31, 26))
        self.checkBox_64.setText(_fromUtf8(""))
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.CoherentMapPlotGraphLabel = QtGui.QLabel(self.frame_40)
        self.CoherentMapPlotGraphLabel.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.CoherentMapPlotGraphLabel.setObjectName(_fromUtf8("CoherentMapPlotGraphLabel"))
        self.CoherentMapPlotGraphceb = QtGui.QCheckBox(self.frame_40)
        self.CoherentMapPlotGraphceb.setGeometry(QtCore.QRect(150, 100, 31, 21))
        self.CoherentMapPlotGraphceb.setText(_fromUtf8(""))
        self.CoherentMapPlotGraphceb.setObjectName(_fromUtf8("CoherentMapPlotGraphceb"))
        self.CoherenMapGraphSave = QtGui.QCheckBox(self.frame_40)
        self.CoherenMapGraphSave.setGeometry(QtCore.QRect(210, 100, 31, 21))
        self.CoherenMapGraphSave.setText(_fromUtf8(""))
        self.CoherenMapGraphSave.setObjectName(_fromUtf8("CoherenMapGraphSave"))
        self.SpectraPlotGraphLabel_2 = QtGui.QLabel(self.frame_40)
        self.SpectraPlotGraphLabel_2.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.SpectraPlotGraphLabel_2.setObjectName(_fromUtf8("SpectraPlotGraphLabel_2"))
        self.SpectraPlotGraphCEB_2 = QtGui.QCheckBox(self.frame_40)
        self.SpectraPlotGraphCEB_2.setGeometry(QtCore.QRect(150, 10, 31, 26))
        self.SpectraPlotGraphCEB_2.setText(_fromUtf8(""))
        self.SpectraPlotGraphCEB_2.setObjectName(_fromUtf8("SpectraPlotGraphCEB_2"))
        self.checkBox_61 = QtGui.QCheckBox(self.frame_40)
        self.checkBox_61.setGeometry(QtCore.QRect(210, 10, 31, 26))
        self.checkBox_61.setText(_fromUtf8(""))
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.dataGraphSpecOkBtn = QtGui.QPushButton(self.tab_10)
        self.dataGraphSpecOkBtn.setGeometry(QtCore.QRect(70, 280, 71, 21))
        self.dataGraphSpecOkBtn.setObjectName(_fromUtf8("dataGraphSpecOkBtn"))
        self.frame_41 = QtGui.QFrame(self.tab_10)
        self.frame_41.setGeometry(QtCore.QRect(10, 220, 261, 51))
        self.frame_41.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_41.setObjectName(_fromUtf8("frame_41"))
        self.label_87 = QtGui.QLabel(self.frame_41)
        self.label_87.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.label_88 = QtGui.QLabel(self.frame_41)
        self.label_88.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.lineEdit_37 = QtGui.QLineEdit(self.frame_41)
        self.lineEdit_37.setGeometry(QtCore.QRect(90, 30, 111, 16))
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.toolButton_18 = QtGui.QToolButton(self.frame_41)
        self.toolButton_18.setGeometry(QtCore.QRect(210, 30, 21, 16))
        self.toolButton_18.setObjectName(_fromUtf8("toolButton_18"))
        self.comboBox_27 = QtGui.QComboBox(self.frame_41)
        self.comboBox_27.setGeometry(QtCore.QRect(90, 10, 141, 16))
        self.comboBox_27.setObjectName(_fromUtf8("comboBox_27"))
        self.label_78 = QtGui.QLabel(self.tab_10)
        self.label_78.setGeometry(QtCore.QRect(20, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.lineEdit_35 = QtGui.QLineEdit(self.tab_10)
        self.lineEdit_35.setGeometry(QtCore.QRect(70, 10, 161, 16))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.toolButton_17 = QtGui.QToolButton(self.tab_10)
        self.toolButton_17.setGeometry(QtCore.QRect(250, 10, 21, 20))
        self.toolButton_17.setObjectName(_fromUtf8("toolButton_17"))
        self.label_80 = QtGui.QLabel(self.tab_10)
        self.label_80.setGeometry(QtCore.QRect(20, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.label_81 = QtGui.QLabel(self.tab_10)
        self.label_81.setGeometry(QtCore.QRect(140, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.label_82 = QtGui.QLabel(self.tab_10)
        self.label_82.setGeometry(QtCore.QRect(210, 30, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.tabWidgetSpec.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.label_22 = QtGui.QLabel(self.tab_11)
        self.label_22.setGeometry(QtCore.QRect(140, 100, 58, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.frame_47 = QtGui.QFrame(self.tab_11)
        self.frame_47.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.frame_47.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_47.setObjectName(_fromUtf8("frame_47"))
        self.label_20 = QtGui.QLabel(self.frame_47)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 22, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_47)
        self.lineEdit_11.setGeometry(QtCore.QRect(50, 10, 151, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.toolButton_5 = QtGui.QToolButton(self.frame_47)
        self.toolButton_5.setGeometry(QtCore.QRect(220, 10, 25, 19))
        self.toolButton_5.setObjectName(_fromUtf8("toolButton_5"))
        self.label_21 = QtGui.QLabel(self.frame_47)
        self.label_21.setGeometry(QtCore.QRect(20, 40, 24, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_47)
        self.lineEdit_12.setGeometry(QtCore.QRect(50, 40, 191, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.frame_49 = QtGui.QFrame(self.tab_11)
        self.frame_49.setGeometry(QtCore.QRect(10, 130, 261, 41))
        self.frame_49.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_49.setObjectName(_fromUtf8("frame_49"))
        self.datasaveSpecOkBtn = QtGui.QPushButton(self.frame_49)
        self.datasaveSpecOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.datasaveSpecOkBtn.setObjectName(_fromUtf8("datasaveSpecOkBtn"))
        self.datasaveSpecCancelBtn = QtGui.QPushButton(self.frame_49)
        self.datasaveSpecCancelBtn.setGeometry(QtCore.QRect(130, 10, 71, 21))
        self.datasaveSpecCancelBtn.setObjectName(_fromUtf8("datasaveSpecCancelBtn"))
        self.tabWidgetSpec.addTab(self.tab_11, _fromUtf8(""))
        self.tabWidgetProject.addTab(self.tabSpectra, _fromUtf8(""))
        self.tabCorrelation = QtGui.QWidget()
        self.tabCorrelation.setObjectName(_fromUtf8("tabCorrelation"))
        self.tabWidgetCor = QtGui.QTabWidget(self.tabCorrelation)
        self.tabWidgetCor.setGeometry(QtCore.QRect(10, 10, 291, 311))
        self.tabWidgetCor.setObjectName(_fromUtf8("tabWidgetCor"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.checkBox_53 = QtGui.QCheckBox(self.tab_12)
        self.checkBox_53.setGeometry(QtCore.QRect(20, 30, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setObjectName(_fromUtf8("checkBox_53"))
        self.comboBox_24 = QtGui.QComboBox(self.tab_12)
        self.comboBox_24.setGeometry(QtCore.QRect(160, 30, 111, 20))
        self.comboBox_24.setObjectName(_fromUtf8("comboBox_24"))
        self.dataopCorrOkBtn = QtGui.QPushButton(self.tab_12)
        self.dataopCorrOkBtn.setGeometry(QtCore.QRect(50, 160, 71, 21))
        self.dataopCorrOkBtn.setObjectName(_fromUtf8("dataopCorrOkBtn"))
        self.dataopCorrCancelBtn = QtGui.QPushButton(self.tab_12)
        self.dataopCorrCancelBtn.setGeometry(QtCore.QRect(170, 160, 71, 21))
        self.dataopCorrCancelBtn.setObjectName(_fromUtf8("dataopCorrCancelBtn"))
        self.tabWidgetCor.addTab(self.tab_12, _fromUtf8(""))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.frame_44 = QtGui.QFrame(self.tab_13)
        self.frame_44.setGeometry(QtCore.QRect(10, 80, 261, 21))
        self.frame_44.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_44.setObjectName(_fromUtf8("frame_44"))
        self.label_95 = QtGui.QLabel(self.frame_44)
        self.label_95.setGeometry(QtCore.QRect(10, 0, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.label_96 = QtGui.QLabel(self.frame_44)
        self.label_96.setGeometry(QtCore.QRect(130, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_96.setFont(font)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.label_97 = QtGui.QLabel(self.frame_44)
        self.label_97.setGeometry(QtCore.QRect(190, 0, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.frame_42 = QtGui.QFrame(self.tab_13)
        self.frame_42.setGeometry(QtCore.QRect(10, 170, 261, 61))
        self.frame_42.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_42.setObjectName(_fromUtf8("frame_42"))
        self.label_89 = QtGui.QLabel(self.frame_42)
        self.label_89.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.label_90 = QtGui.QLabel(self.frame_42)
        self.label_90.setGeometry(QtCore.QRect(10, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_90.setFont(font)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.lineEdit_38 = QtGui.QLineEdit(self.frame_42)
        self.lineEdit_38.setGeometry(QtCore.QRect(90, 30, 101, 16))
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.toolButton_19 = QtGui.QToolButton(self.frame_42)
        self.toolButton_19.setGeometry(QtCore.QRect(200, 30, 21, 16))
        self.toolButton_19.setObjectName(_fromUtf8("toolButton_19"))
        self.comboBox_28 = QtGui.QComboBox(self.frame_42)
        self.comboBox_28.setGeometry(QtCore.QRect(90, 10, 131, 16))
        self.comboBox_28.setObjectName(_fromUtf8("comboBox_28"))
        self.frame_43 = QtGui.QFrame(self.tab_13)
        self.frame_43.setGeometry(QtCore.QRect(10, 110, 261, 51))
        self.frame_43.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_43.setObjectName(_fromUtf8("frame_43"))
        self.label_91 = QtGui.QLabel(self.frame_43)
        self.label_91.setGeometry(QtCore.QRect(20, 10, 66, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.checkBox_67 = QtGui.QCheckBox(self.frame_43)
        self.checkBox_67.setGeometry(QtCore.QRect(140, 10, 31, 26))
        self.checkBox_67.setText(_fromUtf8(""))
        self.checkBox_67.setObjectName(_fromUtf8("checkBox_67"))
        self.checkBox_68 = QtGui.QCheckBox(self.frame_43)
        self.checkBox_68.setGeometry(QtCore.QRect(190, 10, 31, 26))
        self.checkBox_68.setText(_fromUtf8(""))
        self.checkBox_68.setObjectName(_fromUtf8("checkBox_68"))
        self.dataGraphCorrOkBtn = QtGui.QPushButton(self.tab_13)
        self.dataGraphCorrOkBtn.setGeometry(QtCore.QRect(60, 240, 71, 21))
        self.dataGraphCorrOkBtn.setObjectName(_fromUtf8("dataGraphCorrOkBtn"))
        self.dataGraphCorrCancelBtn = QtGui.QPushButton(self.tab_13)
        self.dataGraphCorrCancelBtn.setGeometry(QtCore.QRect(150, 240, 71, 21))
        self.dataGraphCorrCancelBtn.setObjectName(_fromUtf8("dataGraphCorrCancelBtn"))
        self.label_98 = QtGui.QLabel(self.tab_13)
        self.label_98.setGeometry(QtCore.QRect(20, 10, 66, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_98.setFont(font)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.tab_13)
        self.label_99.setGeometry(QtCore.QRect(20, 40, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.lineEdit_39 = QtGui.QLineEdit(self.tab_13)
        self.lineEdit_39.setGeometry(QtCore.QRect(60, 10, 171, 21))
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.toolButton_20 = QtGui.QToolButton(self.tab_13)
        self.toolButton_20.setGeometry(QtCore.QRect(240, 10, 31, 21))
        self.toolButton_20.setObjectName(_fromUtf8("toolButton_20"))
        self.lineEdit_40 = QtGui.QLineEdit(self.tab_13)
        self.lineEdit_40.setGeometry(QtCore.QRect(60, 40, 211, 21))
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.tabWidgetCor.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.label_17 = QtGui.QLabel(self.tab_14)
        self.label_17.setGeometry(QtCore.QRect(140, 100, 58, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.frame_46 = QtGui.QFrame(self.tab_14)
        self.frame_46.setGeometry(QtCore.QRect(10, 20, 261, 71))
        self.frame_46.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_46.setObjectName(_fromUtf8("frame_46"))
        self.label_18 = QtGui.QLabel(self.frame_46)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_46)
        self.lineEdit_9.setGeometry(QtCore.QRect(50, 10, 161, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.toolButton_4 = QtGui.QToolButton(self.frame_46)
        self.toolButton_4.setGeometry(QtCore.QRect(220, 10, 25, 19))
        self.toolButton_4.setObjectName(_fromUtf8("toolButton_4"))
        self.label_19 = QtGui.QLabel(self.frame_46)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_46)
        self.lineEdit_10.setGeometry(QtCore.QRect(50, 40, 191, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.frame_50 = QtGui.QFrame(self.tab_14)
        self.frame_50.setGeometry(QtCore.QRect(10, 140, 261, 41))
        self.frame_50.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_50.setObjectName(_fromUtf8("frame_50"))
        self.datasaveCorrOkBtn = QtGui.QPushButton(self.frame_50)
        self.datasaveCorrOkBtn.setGeometry(QtCore.QRect(30, 10, 71, 21))
        self.datasaveCorrOkBtn.setObjectName(_fromUtf8("datasaveCorrOkBtn"))
        self.dataSaveCorrCancelBtn = QtGui.QPushButton(self.frame_50)
        self.dataSaveCorrCancelBtn.setGeometry(QtCore.QRect(150, 10, 71, 21))
        self.dataSaveCorrCancelBtn.setObjectName(_fromUtf8("dataSaveCorrCancelBtn"))
        self.tabWidgetCor.addTab(self.tab_14, _fromUtf8(""))
        self.tabWidgetProject.addTab(self.tabCorrelation, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.frame_7)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 400, 311, 121))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textEdit = Qsci.QsciScintilla(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 291, 81))
        self.textEdit.setToolTip(_fromUtf8(""))
        self.textEdit.setWhatsThis(_fromUtf8(""))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 867, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFILE = QtGui.QMenu(self.menuBar)
        self.menuFILE.setObjectName(_fromUtf8("menuFILE"))
        self.menuRUN = QtGui.QMenu(self.menuBar)
        self.menuRUN.setObjectName(_fromUtf8("menuRUN"))
        self.menuOPTIONS = QtGui.QMenu(self.menuBar)
        self.menuOPTIONS.setObjectName(_fromUtf8("menuOPTIONS"))
        self.menuHELP = QtGui.QMenu(self.menuBar)
        self.menuHELP.setObjectName(_fromUtf8("menuHELP"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuFileAbrirObj = QtGui.QAction(MainWindow)
        self.menuFileAbrirObj.setObjectName(_fromUtf8("menuFileAbrirObj"))
        self.menuFileCrearObj = QtGui.QAction(MainWindow)
        self.menuFileCrearObj.setObjectName(_fromUtf8("menuFileCrearObj"))
        self.menuFileGuardarObj = QtGui.QAction(MainWindow)
        self.menuFileGuardarObj.setObjectName(_fromUtf8("menuFileGuardarObj"))
        self.menuRUNStartObj = QtGui.QAction(MainWindow)
        self.menuRUNStartObj.setObjectName(_fromUtf8("menuRUNStartObj"))
        self.menuRUNPausaObj = QtGui.QAction(MainWindow)
        self.menuRUNPausaObj.setObjectName(_fromUtf8("menuRUNPausaObj"))
        self.menuOptConfigLogfileObj = QtGui.QAction(MainWindow)
        self.menuOptConfigLogfileObj.setObjectName(_fromUtf8("menuOptConfigLogfileObj"))
        self.menuOptConfigserverObj = QtGui.QAction(MainWindow)
        self.menuOptConfigserverObj.setObjectName(_fromUtf8("menuOptConfigserverObj"))
        self.menuHELPAboutObj = QtGui.QAction(MainWindow)
        self.menuHELPAboutObj.setObjectName(_fromUtf8("menuHELPAboutObj"))
        self.menuHELPPrfObj = QtGui.QAction(MainWindow)
        self.menuHELPPrfObj.setObjectName(_fromUtf8("menuHELPPrfObj"))
        self.actOpenObj = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("figure/Open Sign.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpenObj.setIcon(icon)
        self.actOpenObj.setObjectName(_fromUtf8("actOpenObj"))
        self.actSaveObj = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("figure/guardar.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSaveObj.setIcon(icon1)
        self.actSaveObj.setObjectName(_fromUtf8("actSaveObj"))
        self.actPlayObj = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("figure/play.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPlayObj.setIcon(icon2)
        self.actPlayObj.setObjectName(_fromUtf8("actPlayObj"))
        self.actStopObj = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("figure/stop.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStopObj.setIcon(icon3)
        self.actStopObj.setObjectName(_fromUtf8("actStopObj"))
        self.actCreateObj = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("figure/Crear.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actCreateObj.setIcon(icon4)
        self.actCreateObj.setObjectName(_fromUtf8("actCreateObj"))
        self.menuFileCerrarObj = QtGui.QAction(MainWindow)
        self.menuFileCerrarObj.setObjectName(_fromUtf8("menuFileCerrarObj"))
        self.menuFILE.addAction(self.menuFileAbrirObj)
        self.menuFILE.addAction(self.menuFileCrearObj)
        self.menuFILE.addAction(self.menuFileGuardarObj)
        self.menuFILE.addAction(self.menuFileCerrarObj)
        self.menuRUN.addAction(self.menuRUNStartObj)
        self.menuRUN.addAction(self.menuRUNPausaObj)
        self.menuOPTIONS.addAction(self.menuOptConfigLogfileObj)
        self.menuOPTIONS.addAction(self.menuOptConfigserverObj)
        self.menuHELP.addAction(self.menuHELPAboutObj)
        self.menuHELP.addAction(self.menuHELPPrfObj)
        self.menuBar.addAction(self.menuFILE.menuAction())
        self.menuBar.addAction(self.menuRUN.menuAction())
        self.menuBar.addAction(self.menuOPTIONS.menuAction())
        self.menuBar.addAction(self.menuHELP.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actOpenObj)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actCreateObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actSaveObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actPlayObj)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actStopObj)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidgetProject.setCurrentIndex(0)
        self.tabWidgetVol.setCurrentIndex(0)
        self.tabWidgetSpec.setCurrentIndex(0)
        self.tabWidgetCor.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Project Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Project Explorer", None, QtGui.QApplication.UnicodeUTF8))
        self.addprojectBtn.setText(QtGui.QApplication.translate("MainWindow", "PROJECT", None, QtGui.QApplication.UnicodeUTF8))
        self.addUnitProces.setText(QtGui.QApplication.translate("MainWindow", "PROCESSING UNIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "Read Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.readModeCmBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "OffLine", None, QtGui.QApplication.UnicodeUTF8))
        self.readModeCmBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "OnLine", None, QtGui.QApplication.UnicodeUTF8))
        self.dataWaitLine.setText(QtGui.QApplication.translate("MainWindow", "Wait(sec):", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeLine.setText(QtGui.QApplication.translate("MainWindow", "Data type :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathline.setText(QtGui.QApplication.translate("MainWindow", "Data Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeCmbBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTypeCmbBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOperationModeline.setText(QtGui.QApplication.translate("MainWindow", "Project Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataStartLine.setText(QtGui.QApplication.translate("MainWindow", "Start date :", None, QtGui.QApplication.UnicodeUTF8))
        self.dataEndline.setText(QtGui.QApplication.translate("MainWindow", "End date   :", None, QtGui.QApplication.UnicodeUTF8))
        self.LTReferenceRdBtn.setText(QtGui.QApplication.translate("MainWindow", "Local time frame of reference", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.dataInitialTimeLine.setText(QtGui.QApplication.translate("MainWindow", "Start Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataFinelTimeLine.setText(QtGui.QApplication.translate("MainWindow", "Final Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabProject), QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.selecChannelopVolCEB.setText(QtGui.QApplication.translate("MainWindow", "Select Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.selecHeighopVolCEB.setText(QtGui.QApplication.translate("MainWindow", "Select Heights", None, QtGui.QApplication.UnicodeUTF8))
        self.filterCEB.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.profileSelecopVolCEB.setText(QtGui.QApplication.translate("MainWindow", "Profile Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.decodeCEB.setText(QtGui.QApplication.translate("MainWindow", "Decodification", None, QtGui.QApplication.UnicodeUTF8))
        self.coherentIntegrationCEB.setText(QtGui.QApplication.translate("MainWindow", "Coherent Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVol.setTabText(self.tabWidgetVol.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.datalabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPotlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Potencia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPrefixlabelGraphicsVol.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphicsVolPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVol.setTabText(self.tabWidgetVol.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.dataPathlabelOutVol.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.dataOutVolPathBrowse.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.dataSufixlabelOutVol.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveVolOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveVolCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVol.setTabText(self.tabWidgetVol.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabVoltage), QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.nFFTPointOpSpecCEB.setText(QtGui.QApplication.translate("MainWindow", "nFFTPoints", None, QtGui.QApplication.UnicodeUTF8))
        self.selecChannelopSpecCEB.setText(QtGui.QApplication.translate("MainWindow", "Select Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.IncohIntOpSpecCEB.setText(QtGui.QApplication.translate("MainWindow", "Incoh. Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.removedcOpSpecCEB.setText(QtGui.QApplication.translate("MainWindow", "Remove DC", None, QtGui.QApplication.UnicodeUTF8))
        self.removeIntopSpec.setText(QtGui.QApplication.translate("MainWindow", "Remove Interfere", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpec.setTabText(self.tabWidgetSpec.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.RTIPlotGraphLabel.setText(QtGui.QApplication.translate("MainWindow", "RTI", None, QtGui.QApplication.UnicodeUTF8))
        self.SpectraPlotGraphLabel.setText(QtGui.QApplication.translate("MainWindow", "CROSS-SPECTRA", None, QtGui.QApplication.UnicodeUTF8))
        self.NoisePlotGraphLabel.setText(QtGui.QApplication.translate("MainWindow", "NOISE", None, QtGui.QApplication.UnicodeUTF8))
        self.CoherentMapPlotGraphLabel.setText(QtGui.QApplication.translate("MainWindow", "COHERENT MAP", None, QtGui.QApplication.UnicodeUTF8))
        self.SpectraPlotGraphLabel_2.setText(QtGui.QApplication.translate("MainWindow", "SPECTRA", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_87.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_88.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_18.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_17.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_81.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_82.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpec.setTabText(self.tabWidgetSpec.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Data format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveSpecOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveSpecCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpec.setTabText(self.tabWidgetSpec.indexOf(self.tab_11), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabSpectra), QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_53.setText(QtGui.QApplication.translate("MainWindow", "Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataopCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetCor.setTabText(self.tabWidgetCor.indexOf(self.tab_12), QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_95.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_96.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_97.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_89.setText(QtGui.QApplication.translate("MainWindow", "FTP server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_90.setText(QtGui.QApplication.translate("MainWindow", "FTP path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_19.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_91.setText(QtGui.QApplication.translate("MainWindow", "POTENCIA", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataGraphCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_98.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_99.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_20.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetCor.setTabText(self.tabWidgetCor.indexOf(self.tab_13), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Data format", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Sufix", None, QtGui.QApplication.UnicodeUTF8))
        self.datasaveCorrOkBtn.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.dataSaveCorrCancelBtn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetCor.setTabText(self.tabWidgetCor.indexOf(self.tab_14), QtGui.QApplication.translate("MainWindow", "Save Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabCorrelation), QtGui.QApplication.translate("MainWindow", "Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Ouput Branch", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFILE.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRUN.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOPTIONS.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHELP.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFileAbrirObj.setText(QtGui.QApplication.translate("MainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFileCrearObj.setText(QtGui.QApplication.translate("MainWindow", "Crear", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFileGuardarObj.setText(QtGui.QApplication.translate("MainWindow", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRUNStartObj.setText(QtGui.QApplication.translate("MainWindow", "start", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRUNPausaObj.setText(QtGui.QApplication.translate("MainWindow", "pausa", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptConfigLogfileObj.setText(QtGui.QApplication.translate("MainWindow", "configLogfile", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptConfigserverObj.setText(QtGui.QApplication.translate("MainWindow", "NewFTPServer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHELPAboutObj.setText(QtGui.QApplication.translate("MainWindow", "aboutObj", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHELPPrfObj.setText(QtGui.QApplication.translate("MainWindow", "prfObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenObj.setText(QtGui.QApplication.translate("MainWindow", "openObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenObj.setToolTip(QtGui.QApplication.translate("MainWindow", "open file", None, QtGui.QApplication.UnicodeUTF8))
        self.actSaveObj.setText(QtGui.QApplication.translate("MainWindow", "saveObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actSaveObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actPlayObj.setText(QtGui.QApplication.translate("MainWindow", "playObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actPlayObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Play", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopObj.setText(QtGui.QApplication.translate("MainWindow", "stopObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actStopObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.actCreateObj.setText(QtGui.QApplication.translate("MainWindow", "createObj", None, QtGui.QApplication.UnicodeUTF8))
        self.actCreateObj.setToolTip(QtGui.QApplication.translate("MainWindow", "Manage Create", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFileCerrarObj.setText(QtGui.QApplication.translate("MainWindow", "Cerrar", None, QtGui.QApplication.UnicodeUTF8))

class Ui_BasicWindow(Ui_MainWindow):
    
    def setupUi(self, BasicWindow):
        
        Ui_MainWindow.setupUi(self, BasicWindow)
    
    def retranslateUi(self,BasicWindow):
        
        Ui_MainWindow.retranslateUi(self,BasicWindow)
       
       
        
class Ui_AdvancedWindow(Ui_MainWindow):
    
    def setupUi(self, AdvancedWindow):
        
        Ui_MainWindow.setupUi(self, AdvancedWindow)
    
    def retranslateUi(self, AdvancedWindow):
        
        Ui_MainWindow.retranslateUi(self, AdvancedWindow)
        
from PyQt4 import Qsci

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

