# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alex\ericworkspace\UIDOS\MainWindow_21_02_13_v18.ui'
#
# Created: Tue Mar 12 14:20:43 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 680)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.treeProjectExplorer = QtGui.QTreeView(self.splitter_2)
        self.treeProjectExplorer.setObjectName(_fromUtf8("treeProjectExplorer"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidgetProject = QtGui.QTabWidget(self.splitter)
        self.tabWidgetProject.setMinimumSize(QtCore.QSize(0, 278))
        self.tabWidgetProject.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidgetProject.setObjectName(_fromUtf8("tabWidgetProject"))
        self.tabProject = QtGui.QWidget()
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabProject)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.tabProject)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tabProject)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tabProject)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.tabProject)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tabProject)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 9, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.tabProject)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 10, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tabProject)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 12, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tabProject)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 13, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 15, 0, 1, 1)
        self.proOk = QtGui.QPushButton(self.tabProject)
        self.proOk.setObjectName(_fromUtf8("proOk"))
        self.gridLayout_2.addWidget(self.proOk, 15, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(43, 11, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 15, 3, 1, 1)
        self.proClear = QtGui.QPushButton(self.tabProject)
        self.proClear.setObjectName(_fromUtf8("proClear"))
        self.gridLayout_2.addWidget(self.proClear, 15, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(29, 11, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 15, 5, 1, 1)
        self.proName = QtGui.QLineEdit(self.tabProject)
        self.proName.setObjectName(_fromUtf8("proName"))
        self.gridLayout_2.addWidget(self.proName, 0, 1, 1, 5)
        self.proComDataType = QtGui.QComboBox(self.tabProject)
        self.proComDataType.setObjectName(_fromUtf8("proComDataType"))
        self.proComDataType.addItem(_fromUtf8(""))
        self.proComDataType.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.proComDataType, 1, 1, 1, 5)
        self.proDataType = QtGui.QLineEdit(self.tabProject)
        self.proDataType.setObjectName(_fromUtf8("proDataType"))
        self.gridLayout_2.addWidget(self.proDataType, 2, 1, 1, 5)
        self.proDataPath = QtGui.QLineEdit(self.tabProject)
        self.proDataPath.setObjectName(_fromUtf8("proDataPath"))
        self.gridLayout_2.addWidget(self.proDataPath, 3, 2, 1, 4)
        self.proComReadMode = QtGui.QComboBox(self.tabProject)
        self.proComReadMode.setObjectName(_fromUtf8("proComReadMode"))
        self.proComReadMode.addItem(_fromUtf8(""))
        self.proComReadMode.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.proComReadMode, 4, 1, 1, 5)
        self.proComStartDate = QtGui.QComboBox(self.tabProject)
        self.proComStartDate.setObjectName(_fromUtf8("proComStartDate"))
        self.gridLayout_2.addWidget(self.proComStartDate, 9, 1, 1, 5)
        self.proComEndDate = QtGui.QComboBox(self.tabProject)
        self.proComEndDate.setObjectName(_fromUtf8("proComEndDate"))
        self.gridLayout_2.addWidget(self.proComEndDate, 10, 1, 1, 5)
        self.proStartTime = QtGui.QTimeEdit(self.tabProject)
        self.proStartTime.setObjectName(_fromUtf8("proStartTime"))
        self.gridLayout_2.addWidget(self.proStartTime, 12, 1, 1, 5)
        self.proEndTime = QtGui.QTimeEdit(self.tabProject)
        self.proEndTime.setObjectName(_fromUtf8("proEndTime"))
        self.gridLayout_2.addWidget(self.proEndTime, 13, 1, 1, 5)
        self.label_30 = QtGui.QLabel(self.tabProject)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 14, 0, 1, 1)
        self.proDescription = QtGui.QTextEdit(self.tabProject)
        self.proDescription.setObjectName(_fromUtf8("proDescription"))
        self.gridLayout_2.addWidget(self.proDescription, 14, 1, 1, 5)
        self.proToolPath = QtGui.QToolButton(self.tabProject)
        self.proToolPath.setObjectName(_fromUtf8("proToolPath"))
        self.gridLayout_2.addWidget(self.proToolPath, 3, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.tabProject)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 6, 0, 1, 1)
        self.proComWalk = QtGui.QComboBox(self.tabProject)
        self.proComWalk.setObjectName(_fromUtf8("proComWalk"))
        self.proComWalk.addItem(_fromUtf8(""))
        self.proComWalk.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.proComWalk, 6, 1, 1, 5)
        self.label_33 = QtGui.QLabel(self.tabProject)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 8, 0, 1, 1)
        self.proDelay = QtGui.QLineEdit(self.tabProject)
        self.proDelay.setObjectName(_fromUtf8("proDelay"))
        self.gridLayout_2.addWidget(self.proDelay, 8, 1, 1, 3)
        self.proLoadButton = QtGui.QPushButton(self.tabProject)
        self.proLoadButton.setObjectName(_fromUtf8("proLoadButton"))
        self.gridLayout_2.addWidget(self.proLoadButton, 8, 4, 1, 2)
        self.tabWidgetProject.addTab(self.tabProject, _fromUtf8(""))
        self.tabVoltage = QtGui.QWidget()
        self.tabVoltage.setObjectName(_fromUtf8("tabVoltage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabVoltage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidgetVoltage = QtGui.QTabWidget(self.tabVoltage)
        self.tabWidgetVoltage.setObjectName(_fromUtf8("tabWidgetVoltage"))
        self.tabopVoltage = QtGui.QWidget()
        self.tabopVoltage.setObjectName(_fromUtf8("tabopVoltage"))
        self.gridLayout = QtGui.QGridLayout(self.tabopVoltage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.volOpCebChannels = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebChannels.setObjectName(_fromUtf8("volOpCebChannels"))
        self.gridLayout.addWidget(self.volOpCebChannels, 0, 0, 1, 4)
        self.volOpComChannels = QtGui.QComboBox(self.tabopVoltage)
        self.volOpComChannels.setObjectName(_fromUtf8("volOpComChannels"))
        self.volOpComChannels.addItem(_fromUtf8(""))
        self.volOpComChannels.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.volOpComChannels, 1, 0, 1, 3)
        self.volOpChannel = QtGui.QLineEdit(self.tabopVoltage)
        self.volOpChannel.setObjectName(_fromUtf8("volOpChannel"))
        self.gridLayout.addWidget(self.volOpChannel, 1, 3, 1, 3)
        self.volOpCebHeights = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebHeights.setObjectName(_fromUtf8("volOpCebHeights"))
        self.gridLayout.addWidget(self.volOpCebHeights, 2, 0, 1, 2)
        self.volOpComHeights = QtGui.QComboBox(self.tabopVoltage)
        self.volOpComHeights.setObjectName(_fromUtf8("volOpComHeights"))
        self.volOpComHeights.addItem(_fromUtf8(""))
        self.volOpComHeights.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.volOpComHeights, 3, 0, 1, 3)
        self.volOpHeights = QtGui.QLineEdit(self.tabopVoltage)
        self.volOpHeights.setObjectName(_fromUtf8("volOpHeights"))
        self.gridLayout.addWidget(self.volOpHeights, 3, 3, 1, 3)
        self.volOpCebFilter = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebFilter.setObjectName(_fromUtf8("volOpCebFilter"))
        self.gridLayout.addWidget(self.volOpCebFilter, 4, 0, 1, 2)
        self.volOpFilter = QtGui.QLineEdit(self.tabopVoltage)
        self.volOpFilter.setObjectName(_fromUtf8("volOpFilter"))
        self.gridLayout.addWidget(self.volOpFilter, 4, 3, 1, 3)
        self.volOpCebProfile = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebProfile.setObjectName(_fromUtf8("volOpCebProfile"))
        self.gridLayout.addWidget(self.volOpCebProfile, 5, 0, 1, 3)
        self.volOpComProfile = QtGui.QComboBox(self.tabopVoltage)
        self.volOpComProfile.setObjectName(_fromUtf8("volOpComProfile"))
        self.volOpComProfile.addItem(_fromUtf8(""))
        self.volOpComProfile.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.volOpComProfile, 6, 0, 1, 3)
        self.volOpProfile = QtGui.QLineEdit(self.tabopVoltage)
        self.volOpProfile.setObjectName(_fromUtf8("volOpProfile"))
        self.gridLayout.addWidget(self.volOpProfile, 6, 3, 1, 3)
        self.volOpCebDecodification = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebDecodification.setObjectName(_fromUtf8("volOpCebDecodification"))
        self.gridLayout.addWidget(self.volOpCebDecodification, 7, 0, 1, 3)
        self.label_4 = QtGui.QLabel(self.tabopVoltage)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 8, 1, 1, 1)
        self.volOpComCode = QtGui.QComboBox(self.tabopVoltage)
        self.volOpComCode.setObjectName(_fromUtf8("volOpComCode"))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.volOpComCode.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.volOpComCode, 8, 2, 1, 4)
        self.label_5 = QtGui.QLabel(self.tabopVoltage)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 9, 1, 1, 1)
        self.volOpComMode = QtGui.QComboBox(self.tabopVoltage)
        self.volOpComMode.setObjectName(_fromUtf8("volOpComMode"))
        self.volOpComMode.addItem(_fromUtf8(""))
        self.volOpComMode.addItem(_fromUtf8(""))
        self.volOpComMode.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.volOpComMode, 9, 2, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(54, 11, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 12, 0, 1, 1)
        self.volOpOk = QtGui.QPushButton(self.tabopVoltage)
        self.volOpOk.setObjectName(_fromUtf8("volOpOk"))
        self.gridLayout.addWidget(self.volOpOk, 12, 1, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(43, 11, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 12, 3, 1, 1)
        self.volOpClear = QtGui.QPushButton(self.tabopVoltage)
        self.volOpClear.setObjectName(_fromUtf8("volOpClear"))
        self.gridLayout.addWidget(self.volOpClear, 12, 4, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(33, 6, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 12, 5, 1, 1)
        self.volOpCebCohInt = QtGui.QCheckBox(self.tabopVoltage)
        self.volOpCebCohInt.setObjectName(_fromUtf8("volOpCebCohInt"))
        self.gridLayout.addWidget(self.volOpCebCohInt, 10, 0, 1, 3)
        self.volOpCohInt = QtGui.QLineEdit(self.tabopVoltage)
        self.volOpCohInt.setObjectName(_fromUtf8("volOpCohInt"))
        self.gridLayout.addWidget(self.volOpCohInt, 10, 3, 1, 3)
        self.tabWidgetVoltage.addTab(self.tabopVoltage, _fromUtf8(""))
        self.tabgraphVoltage = QtGui.QWidget()
        self.tabgraphVoltage.setObjectName(_fromUtf8("tabgraphVoltage"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabgraphVoltage)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 1, 0, 1, 2)
        spacerItem6 = QtGui.QSpacerItem(40, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 14, 5, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(18, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem7, 14, 3, 1, 1)
        self.volGraphClear = QtGui.QPushButton(self.tabgraphVoltage)
        self.volGraphClear.setObjectName(_fromUtf8("volGraphClear"))
        self.gridLayout_6.addWidget(self.volGraphClear, 14, 4, 1, 1)
        self.volGraphOk = QtGui.QPushButton(self.tabgraphVoltage)
        self.volGraphOk.setObjectName(_fromUtf8("volGraphOk"))
        self.gridLayout_6.addWidget(self.volGraphOk, 14, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(58, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 14, 0, 1, 1)
        self.volGraphChannelList = QtGui.QLineEdit(self.tabgraphVoltage)
        self.volGraphChannelList.setObjectName(_fromUtf8("volGraphChannelList"))
        self.gridLayout_6.addWidget(self.volGraphChannelList, 7, 2, 1, 4)
        self.label_13 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.volGraphToolPath = QtGui.QToolButton(self.tabgraphVoltage)
        self.volGraphToolPath.setObjectName(_fromUtf8("volGraphToolPath"))
        self.gridLayout_6.addWidget(self.volGraphToolPath, 1, 5, 1, 1)
        self.volGraphfreqrange = QtGui.QLineEdit(self.tabgraphVoltage)
        self.volGraphfreqrange.setObjectName(_fromUtf8("volGraphfreqrange"))
        self.gridLayout_6.addWidget(self.volGraphfreqrange, 8, 2, 1, 4)
        self.volGraphCebshow = QtGui.QCheckBox(self.tabgraphVoltage)
        self.volGraphCebshow.setText(_fromUtf8(""))
        self.volGraphCebshow.setObjectName(_fromUtf8("volGraphCebshow"))
        self.gridLayout_6.addWidget(self.volGraphCebshow, 5, 3, 1, 1)
        self.label_50 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_6.addWidget(self.label_50, 4, 5, 1, 1)
        self.label_8 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_49 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_6.addWidget(self.label_49, 4, 3, 1, 1)
        self.volGraphPrefix = QtGui.QLineEdit(self.tabgraphVoltage)
        self.volGraphPrefix.setObjectName(_fromUtf8("volGraphPrefix"))
        self.gridLayout_6.addWidget(self.volGraphPrefix, 2, 2, 1, 4)
        self.volGraphPath = QtGui.QLineEdit(self.tabgraphVoltage)
        self.volGraphPath.setObjectName(_fromUtf8("volGraphPath"))
        self.gridLayout_6.addWidget(self.volGraphPath, 1, 2, 1, 3)
        self.volGraphHeightrange = QtGui.QLineEdit(self.tabgraphVoltage)
        self.volGraphHeightrange.setObjectName(_fromUtf8("volGraphHeightrange"))
        self.gridLayout_6.addWidget(self.volGraphHeightrange, 10, 2, 1, 4)
        self.label_52 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_6.addWidget(self.label_52, 10, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 5, 0, 1, 2)
        self.label_51 = QtGui.QLabel(self.tabgraphVoltage)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_6.addWidget(self.label_51, 8, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 3, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem10, 11, 2, 1, 1)
        self.volGraphCebSave = QtGui.QCheckBox(self.tabgraphVoltage)
        self.volGraphCebSave.setText(_fromUtf8(""))
        self.volGraphCebSave.setObjectName(_fromUtf8("volGraphCebSave"))
        self.gridLayout_6.addWidget(self.volGraphCebSave, 5, 5, 1, 1)
        self.tabWidgetVoltage.addTab(self.tabgraphVoltage, _fromUtf8(""))
        self.taboutputVoltage = QtGui.QWidget()
        self.taboutputVoltage.setObjectName(_fromUtf8("taboutputVoltage"))
        self.gridLayout_12 = QtGui.QGridLayout(self.taboutputVoltage)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_36 = QtGui.QLabel(self.taboutputVoltage)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_12.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.taboutputVoltage)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_12.addWidget(self.label_37, 1, 0, 1, 1)
        self.volOutputPath = QtGui.QLineEdit(self.taboutputVoltage)
        self.volOutputPath.setObjectName(_fromUtf8("volOutputPath"))
        self.gridLayout_12.addWidget(self.volOutputPath, 1, 1, 1, 1)
        self.volOutputToolPath = QtGui.QToolButton(self.taboutputVoltage)
        self.volOutputToolPath.setObjectName(_fromUtf8("volOutputToolPath"))
        self.gridLayout_12.addWidget(self.volOutputToolPath, 1, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.taboutputVoltage)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_12.addWidget(self.label_38, 2, 0, 1, 1)
        self.volOutputSufix = QtGui.QLineEdit(self.taboutputVoltage)
        self.volOutputSufix.setObjectName(_fromUtf8("volOutputSufix"))
        self.gridLayout_12.addWidget(self.volOutputSufix, 2, 1, 1, 1)
        self.volOutputComData = QtGui.QComboBox(self.taboutputVoltage)
        self.volOutputComData.setObjectName(_fromUtf8("volOutputComData"))
        self.volOutputComData.addItem(_fromUtf8(""))
        self.volOutputComData.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.volOutputComData, 0, 1, 1, 2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem11, 3, 1, 1, 1)
        self.tabWidgetVoltage.addTab(self.taboutputVoltage, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidgetVoltage, 0, 1, 1, 1)
        self.tabWidgetProject.addTab(self.tabVoltage, _fromUtf8(""))
        self.tabSpectra = QtGui.QWidget()
        self.tabSpectra.setObjectName(_fromUtf8("tabSpectra"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabSpectra)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidgetSpectra = QtGui.QTabWidget(self.tabSpectra)
        self.tabWidgetSpectra.setObjectName(_fromUtf8("tabWidgetSpectra"))
        self.tabopSpectra = QtGui.QWidget()
        self.tabopSpectra.setObjectName(_fromUtf8("tabopSpectra"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabopSpectra)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.specOpCebCrossSpectra = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebCrossSpectra.setObjectName(_fromUtf8("specOpCebCrossSpectra"))
        self.gridLayout_5.addWidget(self.specOpCebCrossSpectra, 1, 0, 1, 2)
        self.specOpComChannel = QtGui.QComboBox(self.tabopSpectra)
        self.specOpComChannel.setObjectName(_fromUtf8("specOpComChannel"))
        self.specOpComChannel.addItem(_fromUtf8(""))
        self.specOpComChannel.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.specOpComChannel, 5, 0, 1, 2)
        self.specOpChannel = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpChannel.setObjectName(_fromUtf8("specOpChannel"))
        self.gridLayout_5.addWidget(self.specOpChannel, 5, 2, 1, 3)
        self.specOpComHeights = QtGui.QComboBox(self.tabopSpectra)
        self.specOpComHeights.setObjectName(_fromUtf8("specOpComHeights"))
        self.specOpComHeights.addItem(_fromUtf8(""))
        self.specOpComHeights.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.specOpComHeights, 8, 0, 1, 2)
        self.specOpHeights = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpHeights.setObjectName(_fromUtf8("specOpHeights"))
        self.gridLayout_5.addWidget(self.specOpHeights, 8, 2, 1, 3)
        self.specOpCebIncoherent = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebIncoherent.setObjectName(_fromUtf8("specOpCebIncoherent"))
        self.gridLayout_5.addWidget(self.specOpCebIncoherent, 9, 0, 1, 2)
        self.specOpIncoherent = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpIncoherent.setObjectName(_fromUtf8("specOpIncoherent"))
        self.gridLayout_5.addWidget(self.specOpIncoherent, 9, 2, 1, 3)
        self.specOpCebRemoveDC = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebRemoveDC.setObjectName(_fromUtf8("specOpCebRemoveDC"))
        self.gridLayout_5.addWidget(self.specOpCebRemoveDC, 10, 0, 1, 2)
        self.specOpRemoveDC = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpRemoveDC.setObjectName(_fromUtf8("specOpRemoveDC"))
        self.gridLayout_5.addWidget(self.specOpRemoveDC, 10, 2, 1, 3)
        self.specOpCebRemoveInterference = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebRemoveInterference.setObjectName(_fromUtf8("specOpCebRemoveInterference"))
        self.gridLayout_5.addWidget(self.specOpCebRemoveInterference, 11, 0, 1, 2)
        self.specOpRemoveInterference = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpRemoveInterference.setObjectName(_fromUtf8("specOpRemoveInterference"))
        self.gridLayout_5.addWidget(self.specOpRemoveInterference, 11, 2, 1, 3)
        spacerItem12 = QtGui.QSpacerItem(49, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 12, 0, 1, 1)
        self.specOpOk = QtGui.QPushButton(self.tabopSpectra)
        self.specOpOk.setObjectName(_fromUtf8("specOpOk"))
        self.gridLayout_5.addWidget(self.specOpOk, 12, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(46, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 12, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.tabopSpectra)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_5.addWidget(self.pushButton_8, 12, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(35, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 12, 4, 1, 1)
        self.specOpCebHeights = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebHeights.setObjectName(_fromUtf8("specOpCebHeights"))
        self.gridLayout_5.addWidget(self.specOpCebHeights, 6, 0, 1, 1)
        self.specOpCebChannel = QtGui.QCheckBox(self.tabopSpectra)
        self.specOpCebChannel.setObjectName(_fromUtf8("specOpCebChannel"))
        self.gridLayout_5.addWidget(self.specOpCebChannel, 4, 0, 1, 1)
        self.specOppairsList = QtGui.QLineEdit(self.tabopSpectra)
        self.specOppairsList.setObjectName(_fromUtf8("specOppairsList"))
        self.gridLayout_5.addWidget(self.specOppairsList, 3, 2, 1, 3)
        self.specOpnFFTpoints = QtGui.QLineEdit(self.tabopSpectra)
        self.specOpnFFTpoints.setObjectName(_fromUtf8("specOpnFFTpoints"))
        self.gridLayout_5.addWidget(self.specOpnFFTpoints, 0, 2, 1, 3)
        self.label_31 = QtGui.QLabel(self.tabopSpectra)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 3, 0, 1, 2)
        self.label_26 = QtGui.QLabel(self.tabopSpectra)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 2)
        self.tabWidgetSpectra.addTab(self.tabopSpectra, _fromUtf8(""))
        self.tabgraphSpectra = QtGui.QWidget()
        self.tabgraphSpectra.setObjectName(_fromUtf8("tabgraphSpectra"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tabgraphSpectra)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.specGraphPowerprofile = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphPowerprofile.setText(_fromUtf8(""))
        self.specGraphPowerprofile.setObjectName(_fromUtf8("specGraphPowerprofile"))
        self.gridLayout_9.addWidget(self.specGraphPowerprofile, 11, 2, 1, 1)
        self.specGraphSaveRTIfromNoise = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveRTIfromNoise.setText(_fromUtf8(""))
        self.specGraphSaveRTIfromNoise.setObjectName(_fromUtf8("specGraphSaveRTIfromNoise"))
        self.gridLayout_9.addWidget(self.specGraphSaveRTIfromNoise, 10, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_9.addWidget(self.label_43, 4, 2, 1, 2)
        self.label_42 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_9.addWidget(self.label_42, 8, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_9.addWidget(self.label_16, 18, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_9.addWidget(self.label_17, 19, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_9.addWidget(self.label_18, 20, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_9.addWidget(self.label_21, 22, 0, 1, 1)
        self.specGgraphFreq = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphFreq.setObjectName(_fromUtf8("specGgraphFreq"))
        self.gridLayout_9.addWidget(self.specGgraphFreq, 16, 1, 1, 6)
        self.specGgraphHeight = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphHeight.setObjectName(_fromUtf8("specGgraphHeight"))
        self.gridLayout_9.addWidget(self.specGgraphHeight, 18, 1, 1, 6)
        spacerItem15 = QtGui.QSpacerItem(49, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 27, 0, 1, 1)
        self.specGraphOk = QtGui.QPushButton(self.tabgraphSpectra)
        self.specGraphOk.setObjectName(_fromUtf8("specGraphOk"))
        self.gridLayout_9.addWidget(self.specGraphOk, 27, 1, 1, 2)
        spacerItem16 = QtGui.QSpacerItem(39, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem16, 27, 3, 1, 1)
        self.specGraphClear = QtGui.QPushButton(self.tabgraphSpectra)
        self.specGraphClear.setObjectName(_fromUtf8("specGraphClear"))
        self.gridLayout_9.addWidget(self.specGraphClear, 27, 4, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(28, 15, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem17, 27, 5, 1, 2)
        self.specGraphSaveCoherencemap = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveCoherencemap.setText(_fromUtf8(""))
        self.specGraphSaveCoherencemap.setObjectName(_fromUtf8("specGraphSaveCoherencemap"))
        self.gridLayout_9.addWidget(self.specGraphSaveCoherencemap, 9, 5, 1, 1)
        self.specGraphCebCoherencmap = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphCebCoherencmap.setText(_fromUtf8(""))
        self.specGraphCebCoherencmap.setObjectName(_fromUtf8("specGraphCebCoherencmap"))
        self.gridLayout_9.addWidget(self.specGraphCebCoherencmap, 9, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_9.addWidget(self.label_24, 0, 0, 1, 1)
        self.specGraphPrefix = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGraphPrefix.setObjectName(_fromUtf8("specGraphPrefix"))
        self.gridLayout_9.addWidget(self.specGraphPrefix, 2, 1, 1, 6)
        self.specGgraphDbsrange = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphDbsrange.setObjectName(_fromUtf8("specGgraphDbsrange"))
        self.gridLayout_9.addWidget(self.specGgraphDbsrange, 19, 1, 1, 6)
        self.label_46 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_9.addWidget(self.label_46, 11, 0, 1, 1)
        self.label_40 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_9.addWidget(self.label_40, 6, 0, 1, 2)
        self.label_22 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_9.addWidget(self.label_22, 16, 0, 1, 1)
        self.specGraphPath = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGraphPath.setObjectName(_fromUtf8("specGraphPath"))
        self.gridLayout_9.addWidget(self.specGraphPath, 0, 1, 1, 5)
        self.specGgraphPhaserange = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphPhaserange.setObjectName(_fromUtf8("specGgraphPhaserange"))
        self.gridLayout_9.addWidget(self.specGgraphPhaserange, 22, 1, 1, 6)
        self.label_45 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_9.addWidget(self.label_45, 10, 0, 1, 1)
        self.specGraphCebRTIplot = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphCebRTIplot.setText(_fromUtf8(""))
        self.specGraphCebRTIplot.setObjectName(_fromUtf8("specGraphCebRTIplot"))
        self.gridLayout_9.addWidget(self.specGraphCebRTIplot, 8, 2, 1, 1)
        self.specGgraphmagnitud = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphmagnitud.setObjectName(_fromUtf8("specGgraphmagnitud"))
        self.gridLayout_9.addWidget(self.specGgraphmagnitud, 20, 1, 1, 6)
        self.specGraphCebCrossSpectraplot = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphCebCrossSpectraplot.setText(_fromUtf8(""))
        self.specGraphCebCrossSpectraplot.setObjectName(_fromUtf8("specGraphCebCrossSpectraplot"))
        self.gridLayout_9.addWidget(self.specGraphCebCrossSpectraplot, 7, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_9.addWidget(self.label_41, 7, 0, 1, 1)
        self.specGraphRTIfromnoise = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphRTIfromnoise.setText(_fromUtf8(""))
        self.specGraphRTIfromnoise.setObjectName(_fromUtf8("specGraphRTIfromnoise"))
        self.gridLayout_9.addWidget(self.specGraphRTIfromnoise, 10, 2, 1, 1)
        self.specGraphSaveCross = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveCross.setText(_fromUtf8(""))
        self.specGraphSaveCross.setObjectName(_fromUtf8("specGraphSaveCross"))
        self.gridLayout_9.addWidget(self.specGraphSaveCross, 7, 5, 1, 1)
        self.label_44 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_9.addWidget(self.label_44, 9, 0, 1, 1)
        self.specGraphSavePowerprofile = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSavePowerprofile.setText(_fromUtf8(""))
        self.specGraphSavePowerprofile.setObjectName(_fromUtf8("specGraphSavePowerprofile"))
        self.gridLayout_9.addWidget(self.specGraphSavePowerprofile, 11, 5, 1, 1)
        self.specGraphSaveRTIplot = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveRTIplot.setText(_fromUtf8(""))
        self.specGraphSaveRTIplot.setObjectName(_fromUtf8("specGraphSaveRTIplot"))
        self.gridLayout_9.addWidget(self.specGraphSaveRTIplot, 8, 5, 1, 1)
        self.specGraphCebSpectraplot = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphCebSpectraplot.setText(_fromUtf8(""))
        self.specGraphCebSpectraplot.setObjectName(_fromUtf8("specGraphCebSpectraplot"))
        self.gridLayout_9.addWidget(self.specGraphCebSpectraplot, 6, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_9.addWidget(self.label_47, 4, 5, 1, 1)
        self.specGraphSaveSpectra = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveSpectra.setText(_fromUtf8(""))
        self.specGraphSaveSpectra.setObjectName(_fromUtf8("specGraphSaveSpectra"))
        self.gridLayout_9.addWidget(self.specGraphSaveSpectra, 6, 5, 1, 1)
        self.specGgraphTimeRange = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphTimeRange.setObjectName(_fromUtf8("specGgraphTimeRange"))
        self.gridLayout_9.addWidget(self.specGgraphTimeRange, 21, 1, 1, 6)
        self.specGraphToolPath = QtGui.QToolButton(self.tabgraphSpectra)
        self.specGraphToolPath.setObjectName(_fromUtf8("specGraphToolPath"))
        self.gridLayout_9.addWidget(self.specGraphToolPath, 0, 6, 1, 1)
        self.label_20 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_9.addWidget(self.label_20, 21, 0, 1, 1)
        self.specGraphSaveCCF = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSaveCCF.setText(_fromUtf8(""))
        self.specGraphSaveCCF.setObjectName(_fromUtf8("specGraphSaveCCF"))
        self.gridLayout_9.addWidget(self.specGraphSaveCCF, 13, 5, 1, 1)
        self.specGraphPhase = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphPhase.setText(_fromUtf8(""))
        self.specGraphPhase.setObjectName(_fromUtf8("specGraphPhase"))
        self.gridLayout_9.addWidget(self.specGraphPhase, 12, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_9.addWidget(self.label_19, 12, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_9.addWidget(self.label_48, 13, 0, 1, 1)
        self.specGraphSavePhase = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphSavePhase.setText(_fromUtf8(""))
        self.specGraphSavePhase.setObjectName(_fromUtf8("specGraphSavePhase"))
        self.gridLayout_9.addWidget(self.specGraphSavePhase, 12, 5, 1, 1)
        self.specGraphCCF = QtGui.QCheckBox(self.tabgraphSpectra)
        self.specGraphCCF.setText(_fromUtf8(""))
        self.specGraphCCF.setObjectName(_fromUtf8("specGraphCCF"))
        self.gridLayout_9.addWidget(self.specGraphCCF, 13, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem18, 14, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem19, 3, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_9.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tabgraphSpectra)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_9.addWidget(self.label_6, 15, 0, 1, 1)
        self.specGgraphChannelList = QtGui.QLineEdit(self.tabgraphSpectra)
        self.specGgraphChannelList.setObjectName(_fromUtf8("specGgraphChannelList"))
        self.gridLayout_9.addWidget(self.specGgraphChannelList, 15, 1, 1, 6)
        self.tabWidgetSpectra.addTab(self.tabgraphSpectra, _fromUtf8(""))
        self.taboutputSpectra = QtGui.QWidget()
        self.taboutputSpectra.setObjectName(_fromUtf8("taboutputSpectra"))
        self.gridLayout_11 = QtGui.QGridLayout(self.taboutputSpectra)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_39 = QtGui.QLabel(self.taboutputSpectra)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_11.addWidget(self.label_39, 0, 0, 1, 1)
        self.specOutputComData = QtGui.QComboBox(self.taboutputSpectra)
        self.specOutputComData.setObjectName(_fromUtf8("specOutputComData"))
        self.specOutputComData.addItem(_fromUtf8(""))
        self.specOutputComData.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.specOutputComData, 0, 1, 1, 2)
        self.label_34 = QtGui.QLabel(self.taboutputSpectra)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_11.addWidget(self.label_34, 1, 0, 1, 1)
        self.specOutputPath = QtGui.QLineEdit(self.taboutputSpectra)
        self.specOutputPath.setObjectName(_fromUtf8("specOutputPath"))
        self.gridLayout_11.addWidget(self.specOutputPath, 1, 1, 1, 1)
        self.specOutputToolPath = QtGui.QToolButton(self.taboutputSpectra)
        self.specOutputToolPath.setObjectName(_fromUtf8("specOutputToolPath"))
        self.gridLayout_11.addWidget(self.specOutputToolPath, 1, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.taboutputSpectra)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 2, 0, 1, 1)
        self.specOutputSufix = QtGui.QLineEdit(self.taboutputSpectra)
        self.specOutputSufix.setObjectName(_fromUtf8("specOutputSufix"))
        self.gridLayout_11.addWidget(self.specOutputSufix, 2, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem20, 3, 1, 1, 1)
        self.tabWidgetSpectra.addTab(self.taboutputSpectra, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidgetSpectra, 0, 0, 1, 1)
        self.tabWidgetProject.addTab(self.tabSpectra, _fromUtf8(""))
        self.tabCorrelation = QtGui.QWidget()
        self.tabCorrelation.setObjectName(_fromUtf8("tabCorrelation"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tabCorrelation)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabCorrelation)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tabopCorrelation = QtGui.QWidget()
        self.tabopCorrelation.setObjectName(_fromUtf8("tabopCorrelation"))
        self.tabWidget_2.addTab(self.tabopCorrelation, _fromUtf8(""))
        self.tabopCorrelation1 = QtGui.QWidget()
        self.tabopCorrelation1.setObjectName(_fromUtf8("tabopCorrelation1"))
        self.tabWidget_2.addTab(self.tabopCorrelation1, _fromUtf8(""))
        self.gridLayout_13.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidgetProject.addTab(self.tabCorrelation, _fromUtf8(""))
        self.tabConsole = QtGui.QTabWidget(self.splitter)
        self.tabConsole.setMinimumSize(QtCore.QSize(0, 0))
        self.tabConsole.setObjectName(_fromUtf8("tabConsole"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.console = QtGui.QTextEdit(self.tab_5)
        self.console.setObjectName(_fromUtf8("console"))
        self.gridLayout_4.addWidget(self.console, 0, 0, 1, 1)
        self.tabConsole.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidget = QtGui.QTabWidget(self.splitter_2)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabProjectProperty = QtGui.QWidget()
        self.tabProjectProperty.setObjectName(_fromUtf8("tabProjectProperty"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabProjectProperty)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.treeProjectProperties = QtGui.QTreeView(self.tabProjectProperty)
        self.treeProjectProperties.setObjectName(_fromUtf8("treeProjectProperties"))
        self.gridLayout_8.addWidget(self.treeProjectProperties, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabProjectProperty, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuProject = QtGui.QMenu(self.menuBar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionCreate = QtGui.QAction(MainWindow)
        self.actionCreate.setObjectName(_fromUtf8("actionCreate"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpenToolbar = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("figure/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenToolbar.setIcon(icon)
        self.actionOpenToolbar.setObjectName(_fromUtf8("actionOpenToolbar"))
        self.actionCreateToolbar = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("figure/create_class_obj.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateToolbar.setIcon(icon1)
        self.actionCreateToolbar.setObjectName(_fromUtf8("actionCreateToolbar"))
        self.actionSaveToolbar = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("figure/save.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveToolbar.setIcon(icon2)
        self.actionSaveToolbar.setObjectName(_fromUtf8("actionSaveToolbar"))
        self.actionStarToolbar = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("figure/startServer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStarToolbar.setIcon(icon3)
        self.actionStarToolbar.setObjectName(_fromUtf8("actionStarToolbar"))
        self.actionStopToolbar = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("figure/stopServer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopToolbar.setIcon(icon4)
        self.actionStopToolbar.setObjectName(_fromUtf8("actionStopToolbar"))
        self.toolBar.addAction(self.actionOpenToolbar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCreateToolbar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSaveToolbar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStarToolbar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStopToolbar)
        self.toolBar.addSeparator()
        self.menuProject.addAction(self.actionOpen)
        self.menuProject.addAction(self.actionCreate)
        self.menuProject.addAction(self.actionSave)
        self.menuProject.addAction(self.actionClose)
        self.menuRun.addAction(self.actionStart)
        self.menuRun.addAction(self.actionPause)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetProject.setCurrentIndex(0)
        self.tabWidgetVoltage.setCurrentIndex(0)
        self.tabWidgetSpectra.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabConsole.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Project Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "DataType :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "DataPath :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Read Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Star Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "End Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Start Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "End Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.proOk.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.proClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.proComDataType.setItemText(0, QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.proComDataType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.proComReadMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Off Line", None, QtGui.QApplication.UnicodeUTF8))
        self.proComReadMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "On Line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.proToolPath.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Walk :", None, QtGui.QApplication.UnicodeUTF8))
        self.proComWalk.setItemText(0, QtGui.QApplication.translate("MainWindow", "Search 0", None, QtGui.QApplication.UnicodeUTF8))
        self.proComWalk.setItemText(1, QtGui.QApplication.translate("MainWindow", "Search 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.proLoadButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabProject), QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebChannels.setText(QtGui.QApplication.translate("MainWindow", "Select Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComChannels.setItemText(0, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComChannels.setItemText(1, QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebHeights.setText(QtGui.QApplication.translate("MainWindow", "Select  Heights", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComHeights.setItemText(0, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComHeights.setItemText(1, QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebFilter.setText(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebProfile.setText(QtGui.QApplication.translate("MainWindow", "Profile Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComProfile.setItemText(0, QtGui.QApplication.translate("MainWindow", "Profile List", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComProfile.setItemText(1, QtGui.QApplication.translate("MainWindow", "Profile Range List", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebDecodification.setText(QtGui.QApplication.translate("MainWindow", "Decodification", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Barker 3", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Barker 4", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(2, QtGui.QApplication.translate("MainWindow", "Barker 5", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(3, QtGui.QApplication.translate("MainWindow", "Barker 7", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(4, QtGui.QApplication.translate("MainWindow", "Barker 11", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComCode.setItemText(5, QtGui.QApplication.translate("MainWindow", "Barker 13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComMode.setItemText(0, QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComMode.setItemText(1, QtGui.QApplication.translate("MainWindow", "Freq 1", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpComMode.setItemText(2, QtGui.QApplication.translate("MainWindow", "Freq 2", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpOk.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.volOpCebCohInt.setText(QtGui.QApplication.translate("MainWindow", "Coherent Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVoltage.setTabText(self.tabWidgetVoltage.indexOf(self.tabopVoltage), QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.volGraphClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.volGraphOk.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.volGraphToolPath.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Channel List", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "Height range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Scope", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "Freq/Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVoltage.setTabText(self.tabWidgetVoltage.indexOf(self.tabgraphVoltage), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Dataformat:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.volOutputToolPath.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Sufix:", None, QtGui.QApplication.UnicodeUTF8))
        self.volOutputComData.setItemText(0, QtGui.QApplication.translate("MainWindow", ".rawdata", None, QtGui.QApplication.UnicodeUTF8))
        self.volOutputComData.setItemText(1, QtGui.QApplication.translate("MainWindow", ".fits", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetVoltage.setTabText(self.tabWidgetVoltage.indexOf(self.taboutputVoltage), QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabVoltage), QtGui.QApplication.translate("MainWindow", "Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebCrossSpectra.setText(QtGui.QApplication.translate("MainWindow", "Select  Cross Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpComChannel.setItemText(0, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpComChannel.setItemText(1, QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpComHeights.setItemText(0, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpComHeights.setItemText(1, QtGui.QApplication.translate("MainWindow", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebIncoherent.setText(QtGui.QApplication.translate("MainWindow", "Incoherent Integration", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebRemoveDC.setText(QtGui.QApplication.translate("MainWindow", "Remove DC", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebRemoveInterference.setText(QtGui.QApplication.translate("MainWindow", "Remove Interference", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpOk.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebHeights.setText(QtGui.QApplication.translate("MainWindow", "Select Heights", None, QtGui.QApplication.UnicodeUTF8))
        self.specOpCebChannel.setText(QtGui.QApplication.translate("MainWindow", "Select Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "x-y pairs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "nFFTPoints", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpectra.setTabText(self.tabWidgetSpectra.indexOf(self.tabopSpectra), QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "RTI Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Height range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Dbs  range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "magnitud [0-1]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Phase range", None, QtGui.QApplication.UnicodeUTF8))
        self.specGraphOk.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.specGraphClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Power Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Spectra Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Freq/Vel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "RTI from Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Cross Spectra Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "Coherence Map", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.specGraphToolPath.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Time Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("MainWindow", "CCF", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Channel List", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpectra.setTabText(self.tabWidgetSpectra.indexOf(self.tabgraphSpectra), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Data Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.specOutputComData.setItemText(0, QtGui.QApplication.translate("MainWindow", ".pdata", None, QtGui.QApplication.UnicodeUTF8))
        self.specOutputComData.setItemText(1, QtGui.QApplication.translate("MainWindow", ".fits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.specOutputToolPath.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Sufix:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetSpectra.setTabText(self.tabWidgetSpectra.indexOf(self.taboutputSpectra), QtGui.QApplication.translate("MainWindow", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabSpectra), QtGui.QApplication.translate("MainWindow", "Spectra", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabopCorrelation), QtGui.QApplication.translate("MainWindow", "Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabopCorrelation1), QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabCorrelation), QtGui.QApplication.translate("MainWindow", "Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabConsole.setTabText(self.tabConsole.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabProjectProperty), QtGui.QApplication.translate("MainWindow", "Project Property", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRun.setTitle(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenToolbar.setText(QtGui.QApplication.translate("MainWindow", "openToolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenToolbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateToolbar.setText(QtGui.QApplication.translate("MainWindow", "createToolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreateToolbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveToolbar.setText(QtGui.QApplication.translate("MainWindow", "saveToolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveToolbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStarToolbar.setText(QtGui.QApplication.translate("MainWindow", "starToolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStarToolbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStopToolbar.setText(QtGui.QApplication.translate("MainWindow", "stopToolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStopToolbar.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))





class Ui_BasicWindow(Ui_MainWindow):
    
    def setupUi(self, BasicWindow):
        
        Ui_MainWindow.setupUi(self, BasicWindow)
    
    def retranslateUi(self,BasicWindow):
        
        Ui_MainWindow.retranslateUi(self,BasicWindow)
       
       
        
class Ui_AdvancedWindow(Ui_MainWindow):
    
    def setupUi(self, AdvancedWindow):
        
        Ui_MainWindow.setupUi(self, AdvancedWindow)
    
    def retranslateUi(self, AdvancedWindow):
        
        Ui_MainWindow.retranslateUi(self, AdvancedWindow)
        
from PyQt4 import Qsci

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
