from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
    
class Ui_SpectraHeisTab(object):
    
    def setupUi(self):

        self.tabSpectraHeis = QtGui.QWidget()
        self.tabSpectraHeis.setObjectName(_fromUtf8("tabSpectraHeis"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tabSpectraHeis)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.frame_6 = QtGui.QFrame(self.tabSpectraHeis)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.specHeisGraphClear = QtGui.QPushButton(self.frame_6)
        self.specHeisGraphClear.setObjectName(_fromUtf8("specHeisGraphClear"))
        self.gridLayout_22.addWidget(self.specHeisGraphClear, 0, 1, 1, 1)
        self.specHeisOpOk = QtGui.QPushButton(self.frame_6)
        self.specHeisOpOk.setObjectName(_fromUtf8("specHeisOpOk"))
        self.gridLayout_22.addWidget(self.specHeisOpOk, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_6, 1, 0, 1, 1)
        self.tabWidgetSpectraHeis = QtGui.QTabWidget(self.tabSpectraHeis)
        self.tabWidgetSpectraHeis.setObjectName(_fromUtf8("tabWidgetSpectraHeis"))
        self.tabopSpectraHeis = QtGui.QWidget()
        self.tabopSpectraHeis.setObjectName(_fromUtf8("tabopSpectraHeis"))
        self.gridLayout_21 = QtGui.QGridLayout(self.tabopSpectraHeis)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem21, 0, 1, 1, 1)
        self.specHeisOpCobIncInt = QtGui.QComboBox(self.tabopSpectraHeis)
        self.specHeisOpCobIncInt.setObjectName(_fromUtf8("specHeisOpCobIncInt"))
        self.specHeisOpCobIncInt.addItem(_fromUtf8(""))
        self.gridLayout_21.addWidget(self.specHeisOpCobIncInt, 1, 0, 1, 1)
        self.specHeisOpCebIncoherent = QtGui.QCheckBox(self.tabopSpectraHeis)
        self.specHeisOpCebIncoherent.setObjectName(_fromUtf8("specHeisOpCebIncoherent"))
        self.gridLayout_21.addWidget(self.specHeisOpCebIncoherent, 0, 0, 1, 1)
        self.specHeisOpIncoherent = QtGui.QLineEdit(self.tabopSpectraHeis)
        self.specHeisOpIncoherent.setObjectName(_fromUtf8("specHeisOpIncoherent"))
        self.gridLayout_21.addWidget(self.specHeisOpIncoherent, 1, 1, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem22, 2, 0, 1, 1)
        self.tabWidgetSpectraHeis.addTab(self.tabopSpectraHeis, _fromUtf8(""))
        self.tabgraphSpectraHeis = QtGui.QWidget()
        self.tabgraphSpectraHeis.setObjectName(_fromUtf8("tabgraphSpectraHeis"))
        self.gridLayout_20 = QtGui.QGridLayout(self.tabgraphSpectraHeis)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_54 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_20.addWidget(self.label_54, 1, 0, 1, 1)
        self.specHeisGraphToolPath = QtGui.QToolButton(self.tabgraphSpectraHeis)
        self.specHeisGraphToolPath.setObjectName(_fromUtf8("specHeisGraphToolPath"))
        self.gridLayout_20.addWidget(self.specHeisGraphToolPath, 0, 6, 1, 1)
        self.specHeisGraphCebRTIplot = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphCebRTIplot.setText(_fromUtf8(""))
        self.specHeisGraphCebRTIplot.setObjectName(_fromUtf8("specHeisGraphCebRTIplot"))
        self.gridLayout_20.addWidget(self.specHeisGraphCebRTIplot, 4, 2, 1, 1)
        self.label_62 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_20.addWidget(self.label_62, 7, 0, 1, 1)
        self.label_63 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_20.addWidget(self.label_63, 8, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_20.addWidget(self.label_64, 9, 0, 1, 1)
        self.label_65 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_20.addWidget(self.label_65, 10, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(134, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem23, 11, 0, 1, 2)
        self.specHeisGgraphftpratio = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphftpratio.setObjectName(_fromUtf8("specHeisGgraphftpratio"))
        self.gridLayout_20.addWidget(self.specHeisGgraphftpratio, 10, 1, 1, 6)
        self.specHeisGraphftpRTIplot = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphftpRTIplot.setText(_fromUtf8(""))
        self.specHeisGraphftpRTIplot.setObjectName(_fromUtf8("specHeisGraphftpRTIplot"))
        self.gridLayout_20.addWidget(self.specHeisGraphftpRTIplot, 4, 6, 1, 1)
        self.specHeisGgraphTminTmax = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphTminTmax.setObjectName(_fromUtf8("specHeisGgraphTminTmax"))
        self.gridLayout_20.addWidget(self.specHeisGgraphTminTmax, 8, 1, 1, 6)
        self.label_60 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_20.addWidget(self.label_60, 5, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_20.addWidget(self.label_61, 6, 0, 1, 1)
        self.specHeisGraphPrefix = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGraphPrefix.setObjectName(_fromUtf8("specHeisGraphPrefix"))
        self.gridLayout_20.addWidget(self.specHeisGraphPrefix, 1, 1, 1, 6)
        self.label_56 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_20.addWidget(self.label_56, 2, 4, 1, 1)
        self.label_57 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_20.addWidget(self.label_57, 2, 6, 1, 1)
        self.label_58 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_20.addWidget(self.label_58, 3, 0, 1, 1)
        self.specHeisGraphCebSpectraplot = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphCebSpectraplot.setText(_fromUtf8(""))
        self.specHeisGraphCebSpectraplot.setObjectName(_fromUtf8("specHeisGraphCebSpectraplot"))
        self.gridLayout_20.addWidget(self.specHeisGraphCebSpectraplot, 3, 2, 1, 1)
        self.specHeisGgraphYminYmax = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphYminYmax.setObjectName(_fromUtf8("specHeisGgraphYminYmax"))
        self.gridLayout_20.addWidget(self.specHeisGgraphYminYmax, 7, 1, 1, 6)
        self.label_53 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_20.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_55 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_20.addWidget(self.label_55, 2, 2, 1, 1)
        self.specHeisGraphSaveRTIplot = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphSaveRTIplot.setText(_fromUtf8(""))
        self.specHeisGraphSaveRTIplot.setObjectName(_fromUtf8("specHeisGraphSaveRTIplot"))
        self.gridLayout_20.addWidget(self.specHeisGraphSaveRTIplot, 4, 4, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem24, 2, 3, 1, 1)
        self.specHeisGgraphXminXmax = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphXminXmax.setObjectName(_fromUtf8("specHeisGgraphXminXmax"))
        self.gridLayout_20.addWidget(self.specHeisGgraphXminXmax, 6, 1, 1, 6)
        self.specHeisGgraphChannelList = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphChannelList.setObjectName(_fromUtf8("specHeisGgraphChannelList"))
        self.gridLayout_20.addWidget(self.specHeisGgraphChannelList, 5, 1, 1, 6)
        self.specHeisGgraphTimeRange = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGgraphTimeRange.setObjectName(_fromUtf8("specHeisGgraphTimeRange"))
        self.gridLayout_20.addWidget(self.specHeisGgraphTimeRange, 9, 1, 1, 6)
        spacerItem25 = QtGui.QSpacerItem(106, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem25, 11, 3, 1, 3)
        self.specHeisGraphSaveSpectra = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphSaveSpectra.setText(_fromUtf8(""))
        self.specHeisGraphSaveSpectra.setObjectName(_fromUtf8("specHeisGraphSaveSpectra"))
        self.gridLayout_20.addWidget(self.specHeisGraphSaveSpectra, 3, 4, 1, 1)
        self.specHeisGraphftpSpectra = QtGui.QCheckBox(self.tabgraphSpectraHeis)
        self.specHeisGraphftpSpectra.setText(_fromUtf8(""))
        self.specHeisGraphftpSpectra.setObjectName(_fromUtf8("specHeisGraphftpSpectra"))
        self.gridLayout_20.addWidget(self.specHeisGraphftpSpectra, 3, 6, 1, 1)
        self.label_59 = QtGui.QLabel(self.tabgraphSpectraHeis)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_20.addWidget(self.label_59, 4, 0, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem26, 2, 5, 1, 1)
        self.specHeisGraphPath = QtGui.QLineEdit(self.tabgraphSpectraHeis)
        self.specHeisGraphPath.setObjectName(_fromUtf8("specHeisGraphPath"))
        self.gridLayout_20.addWidget(self.specHeisGraphPath, 0, 1, 1, 5)
        self.tabWidgetSpectraHeis.addTab(self.tabgraphSpectraHeis, _fromUtf8(""))
        self.taboutputSpectraHeis = QtGui.QWidget()
        self.taboutputSpectraHeis.setObjectName(_fromUtf8("taboutputSpectraHeis"))
        self.gridLayout_19 = QtGui.QGridLayout(self.taboutputSpectraHeis)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_67 = QtGui.QLabel(self.taboutputSpectraHeis)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_19.addWidget(self.label_67, 1, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.taboutputSpectraHeis)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_19.addWidget(self.label_68, 2, 0, 1, 2)
        self.label_66 = QtGui.QLabel(self.taboutputSpectraHeis)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_19.addWidget(self.label_66, 0, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem27, 4, 0, 1, 1)
        self.specHeisOutputToolPath = QtGui.QToolButton(self.taboutputSpectraHeis)
        self.specHeisOutputToolPath.setObjectName(_fromUtf8("specHeisOutputToolPath"))
        self.gridLayout_19.addWidget(self.specHeisOutputToolPath, 1, 4, 1, 1)
        self.specHeisOutputPath = QtGui.QLineEdit(self.taboutputSpectraHeis)
        self.specHeisOutputPath.setObjectName(_fromUtf8("specHeisOutputPath"))
        self.gridLayout_19.addWidget(self.specHeisOutputPath, 1, 3, 1, 1)
        self.specHeisOutputComdata = QtGui.QComboBox(self.taboutputSpectraHeis)
        self.specHeisOutputComdata.setObjectName(_fromUtf8("specHeisOutputComdata"))
        self.specHeisOutputComdata.addItem(_fromUtf8(""))
        self.gridLayout_19.addWidget(self.specHeisOutputComdata, 0, 3, 1, 2)
        self.label_69 = QtGui.QLabel(self.taboutputSpectraHeis)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_19.addWidget(self.label_69, 3, 0, 1, 2)
        self.specHeisOutputblocksperfile = QtGui.QLineEdit(self.taboutputSpectraHeis)
        self.specHeisOutputblocksperfile.setObjectName(_fromUtf8("specHeisOutputblocksperfile"))
        self.gridLayout_19.addWidget(self.specHeisOutputblocksperfile, 2, 3, 1, 1)
        self.specHeisOutputMetada = QtGui.QLineEdit(self.taboutputSpectraHeis)
        self.specHeisOutputMetada.setObjectName(_fromUtf8("specHeisOutputMetada"))
        self.gridLayout_19.addWidget(self.specHeisOutputMetada, 3, 3, 1, 1)
        self.specHeisOutputMetadaToolPath = QtGui.QToolButton(self.taboutputSpectraHeis)
        self.specHeisOutputMetadaToolPath.setObjectName(_fromUtf8("specHeisOutputMetadaToolPath"))
        self.gridLayout_19.addWidget(self.specHeisOutputMetadaToolPath, 3, 4, 1, 1)
        self.tabWidgetSpectraHeis.addTab(self.taboutputSpectraHeis, _fromUtf8(""))
        self.gridLayout_23.addWidget(self.tabWidgetSpectraHeis, 0, 0, 1, 1)
        
        self.tabWidgetProject.addTab(self.tabSpectraHeis, _fromUtf8(""))
        
        self.tabWidgetSpectraHeis.setCurrentIndex(0)
        
    def retranslateUi(self):
        
        self.specHeisGraphClear.setText(_translate("MainWindow", "Clear", None))
        self.specHeisOpOk.setText(_translate("MainWindow", "Ok", None))
        self.specHeisOpCobIncInt.setItemText(0, _translate("MainWindow", "Time Interval", None))
        self.specHeisOpCebIncoherent.setText(_translate("MainWindow", "Incoherent Intergration", None))
        
        self.tabWidgetSpectraHeis.setTabText(self.tabWidgetSpectraHeis.indexOf(self.tabopSpectraHeis), _translate("MainWindow", "Operation", None))
        self.label_54.setText(_translate("MainWindow", "Prefix", None))
        self.specHeisGraphToolPath.setText(_translate("MainWindow", "...", None))
        self.label_62.setText(_translate("MainWindow", "Intensity range (dB)", None))
        self.label_63.setText(_translate("MainWindow", "Time range (hours):", None))
        self.label_64.setText(_translate("MainWindow", "Time interval:", None))
        self.label_65.setText(_translate("MainWindow", "Wr Period", None))
        self.label_60.setText(_translate("MainWindow", "Channel List:", None))
        self.label_61.setText(_translate("MainWindow", "Frequency range", None))
        self.label_56.setText(_translate("MainWindow", "Save", None))
        self.label_57.setText(_translate("MainWindow", "ftp", None))
        self.label_58.setText(_translate("MainWindow", "Spectra Plot", None))
        self.label_53.setText(_translate("MainWindow", "Path", None))
        self.label_55.setText(_translate("MainWindow", "Show", None))
        self.label_59.setText(_translate("MainWindow", "RTI Plot", None))
        
        self.tabWidgetSpectraHeis.setTabText(self.tabWidgetSpectraHeis.indexOf(self.tabgraphSpectraHeis), _translate("MainWindow", "Graphics", None))
        self.label_67.setText(_translate("MainWindow", "Path:", None))
        self.label_68.setText(_translate("MainWindow", "Blocks  per File:", None))
        self.label_66.setText(_translate("MainWindow", "Type:", None))
        
        self.tabWidgetSpectraHeis.setTabText(self.tabWidgetSpectraHeis.indexOf(self.taboutputSpectraHeis), _translate("MainWindow", "Output", None))
        self.specHeisOutputToolPath.setText(_translate("MainWindow", "...", None))
        self.specHeisOutputComdata.setItemText(0, _translate("MainWindow", ".fits", None))
        self.label_69.setText(_translate("MainWindow", "Metada", None))
        self.specHeisOutputMetadaToolPath.setText(_translate("MainWindow", "...", None))
        
        self.tabWidgetProject.setTabText(self.tabWidgetProject.indexOf(self.tabSpectraHeis), _translate("MainWindow", "SpectraHeis", None))
